### ISSUE TITLE
Bots standing still at certain place and do not perform any actions

### ISSUE THREAD

**Issue by harmonyzt** [Solarint/SAIN#10]
I've seen this issue happening a lot when some of the bots (let it be pmc or a scav) just get to their position, stand pointlessly and not doing anything or even shoot you until you get too close to them or they will just stare at you and still won't do much to get you. Is this somewhat hardcoded into the game?

If you have played a game enough you could probably notice some pmcs just get stuck in the building on reserve (Headquarters, Bishop / Building with tetrises) just looking at the wall and most likely will stand there for the entire raid until they get killed by someone.

I have marked a place where exactly they stand (1st floor). Of course it happens on other maps but haven't seen it much. Any tips?
![image](https://github.com/Solarint/SAIN/assets/61928705/5135c53b-783e-4832-bc14-16108df89df6)
![firefox_0fTHWBaGw4](https://github.com/Solarint/SAIN/assets/61928705/52215b56-3b33-4752-a7b8-a3605d79ae21)

**Comment by harmonyzt** [comment]
Forgot to mention, same thing happens on factory. It always happens to be a pmc which will always stand at the exact place through the entire raid.
![firefox_3M2pgkj7Q7](https://github.com/Solarint/SAIN/assets/61928705/01153f64-76f3-4bdd-aaea-92b314bcd1e3)

If needed, the only mods I had installed are SWAG, Looting Bots, Extended Waypoints and your AIO Pack.

**Comment by Solarint** [comment]
I've noticed bots getting stuck at that place on reserve even before I started modding. I think its a vanilla issue in the map. Not sure about the factory one, but I'll keep an eye out and see if its caused by SAIN.

**Comment by harmonyzt** [comment]
I am also pretty sure it's just vanilla issue, I guess there's no work around to just force bots to roam around instead of standing in one place for too long?
