### ISSUE TITLE
bots sometimes jerking around when aiming at an enemy

### ISSUE THREAD

**Issue by NoclubOIRzXx** [Solarint/SAIN#105]
When I aim at AI, it goes haywire with its targeting

I used the default settings of the MOD, and both PMC and Scavs exhibited jerky behavior. After removing the MOD, the AI's behavior returned to normal.

MOD version:SAIN 2.1.5

SPT-AKI version: 3.7.1

server-side MOD : [server-side MOD](https://prnt.sc/bU99wwUpQJfB)
client-side MOD :[client-side MOD](https://prnt.sc/w_TIWzN8vpww)

video showcase:
[SAIN problem](https://www.youtube.com/watch?v=rpRY_y9pnNs)

[ETF vanilla](https://www.youtube.com/watch?v=nu8mtZI5a1o)

**Comment by Solarint** [comment]
still haven't figured out exactly what causes this, its less bad now, but still happens. Need to deep dive into eft code to see what is being set incorrectly in SAIN.

**Comment by Solarint** [comment]
Should be fixed now.
