### ISSUE TITLE
SAIN 2.0 Wrong version 

### ISSUE THREAD

**Issue by C0AX0728** [Solarint/SAIN#106]
the plugin is loading through the server, but in game it is saying "ERROR: The version of SAIN v2.1.4 was built for Tarkov 26282, but you are running 26535. please download the correct plugin version."

I have tried to redownload SAIN to make sure I have the newest version, as well as attempted to downgrade the AKI, but Nothing has resolved.

is this a known thing, or is it just the version is out of date?

I have attached my output anyway  
[LogOutput.log](https://github.com/Solarint/SAIN/files/13271867/LogOutput.log)

**Comment by DrakiaXYZ** [comment]
You either have a duplicate SAIN DLL file under `BepInEx/plugins` or you're downloading the wrong version. The latest SAIN release is 2.1.5: https://github.com/Solarint/SAIN/releases/tag/3.5.7

**Comment by C0AX0728** [comment]
I figured it out it was a duplicate BepinEx folder hahah. No idea why
