### ISSUE TITLE
(3.5.7 Beta 6) PMC AI is standing still while keeping their eyes on me

### ISSUE THREAD

**Issue by sleeva1337** [Solarint/SAIN#11]

**Comment by sleeva1337** [comment]
Sometimes I've got some PMC that don't want to engage on me while screaming that they have contact. https://youtu.be/DW4Wny5jghg?t=235 (3:50 - the end of the video). The first two that I kill don't shoot back because, probably, of No Bush ESP mod. But the last one still didn't move an inch since he first saw me running and shooting behind the fence and getting close on him.

The list of mods I have: SPT 3.5.7, POOP + POOP Variety, SWAG + SWAG Variety, NoBushESP, ItemInfo, MoreCheckmarks, Waypoints, Softcore, Amand's graphics, nodiscardlimit and SAIN 3.5.7 Beta 6.

BTW sorry for poor editing skills I accidently pressed enter while typing topic name.

**Comment by Solarint** [comment]
Hard to find the source of this, but I adjusted a few things and it seems less common now on test build 7, which i just released. Let me know if it still happens. https://github.com/Solarint/SAIN/releases/tag/2.1
