### ISSUE TITLE
GrenadeTracker component EnemyGrenadeHeard seems to spam errors

### ISSUE THREAD

**Issue by vizorian** [Solarint/SAIN#111]
Hi,
I noticed I have Null ref exceptions pop up from time to time, look like this:
[Error sample.txt](https://github.com/Solarint/SAIN/files/13404640/Error.sample.txt)

My current mods:
![image](https://github.com/Solarint/SAIN/assets/14858098/263d07c2-f8e4-47e2-b157-7ab432f93d4e)

Note: these have been installed (hopefully) properly. I checked all compatibility and installation documentation multiple times, the load orders, etc.

**Comment by LukaLake** [comment]
I'm having exactly the same problem

**Comment by Solarint** [comment]
Should be fixed in recent versions.
