### ISSUE TITLE
Flashlight global settings and silly mode not working.

### ISSUE THREAD

**Issue by Diplow187** [Solarint/SAIN#112]
Spt version 3.7.3

MODS
questing bots
Algorithmic level progression
Gunsmith
Iteminfo
The blacklist 
Realistic thermals
Server value modifier
Skwizzy looting bots
Swag
Levelrewards
Welcome gifts
Lots of loot
Sain
Waypoints

I remember when pointing a laser or flashlight on a bot would make them go nuts with silly mode on. Shouting at you and just shooting all over the place. 

Now with ramping up the setting in f6 and even silly mode on the bots seem unaffected

**Comment by Solarint** [comment]
Was never able to reproduce this.
