### ISSUE TITLE
3.5.7 beta | i cant extract or die. it just stays in game forever and never goes to main menu/post raid screen

### ISSUE THREAD

**Issue by ASwedishGamer** [Solarint/SAIN#12]

**Comment by ASwedishGamer** [comment]
i will test to see if its a compatability issue or just the mod creating the issue

**Comment by atredies-01** [comment]
likewise having this issue, reinstalled ver 6 beta and it seems to have gone away

**Comment by ASwedishGamer** [comment]
i tested and it is not a compatability issue it happens without any other mods as well

**Comment by ASwedishGamer** [comment]
> likewise having this issue, reinstalled ver 6 beta and it seems to have gone away

how do i download ver 6 instead of 7?

**Comment by Juliozer** [comment]
Try the last version 8.1. It work perfectly for me.
