### ISSUE TITLE
Feature request: Config to disable sain AI in selected bots.

### ISSUE THREAD

**Issue by EngHell** [Solarint/SAIN#122]
Hello, first thanks for the great mod, I really like it, but if possible I would like to have vanilla experience with the following bots:

- The Goons
- All the bosses
- Bosses' guards
- Rogues
- Raiders
- Scav Snipers

I've noticed that the default SAIN settings for those AIs are a bit mild for me, and I would preffer a vanilla experience in those PVE aspects

**Comment by Solarint** [comment]
I've looked at ways to implement this, and its something I'll do eventually. but to put it mildly - its complicated.

**Comment by EngHell** [comment]
@Solarint thanks for the notice, I appreciate you taking the time to look into that.
