### ISSUE TITLE
SAIN error filling logs

### ISSUE THREAD

**Issue by gri4ka** [Solarint/SAIN#123]
SPT 3.8.1;
Mods: FIKA, Item Info, Waypoints, BigBrain, Sain, Looting Bots, Questing Bots

The game crashed 2 times already, and checking the logs leads me towards SAIN. I will continue investigating the crash myself, but I would like to bring it up here too just in case.

[LogOutput.log](https://github.com/Solarint/SAIN/files/15239574/LogOutput.log)

The localLow tarkov log(C:\Users*user*\AppData\LocalLow\Battlestate Games\EscapeFromTarkov) is filled with this error, however the full log is too big for github.
NullReferenceException: Object reference not set to an instance of an object
at SAIN.SAINComponent.Classes.SAINEnemyController.UpdateEnemies () [0x00057] in <60e2491a84284e61866938ab687f4b67>:0
at SAIN.SAINComponent.Classes.SAINEnemyController.Update () [0x00000] in <60e2491a84284e61866938ab687f4b67>:0
at SAIN.SAINComponent.SAINComponentClass.Update () [0x0006b] in <60e2491a84284e61866938ab687f4b67>:0
UnityEngine.DebugLogHandler:Internal_LogException(Exception, Object)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
Class358:UnityEngine.ILogHandler.LogException(Exception, Object)
UnityEngine.Logger:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

(Filename: <60e2491a84284e61866938ab687f4b67> Line: 0)

**Comment by gri4ka** [comment]
Just saw there was a similar issue and it seems to come from EFT. Any suggestions on a workaround? ATM EFT is taking up all available ram and occasionally crashing, most likely due to that.

**Comment by Solarint** [comment]
If you are using fika, you should use the builds I'm posting in their discord.
