### ISSUE TITLE
Bot visibility check appears to detect both visible and IR devices?

### ISSUE THREAD

**Issue by GavinRay97** [Solarint/SAIN#124]
I tried asking for clarification about whether IR devices impact bot detection, there didn't seem to be a definitive answer online.

In the source, I can see:
https://github.com/Solarint/SAIN/blob/34116b6103e30e2a2838a5b90847049cbfb2a7d3/Components/MainPlayer/SAINFlashLightComponent.cs#L52-L57

There's a comment in `CheckIRLight` that mentions something about the `Volumetric` tag indicating it's a visible light.
Not sure what exactly the behavior/outcome of this is, and what the intended behavior is 🤔

**Comment by Solarint** [comment]
theres a later check that only lets them see detection points created by IR if they are using nvgs, check your inbox on discord, I replied to you :)
