### ISSUE TITLE
Saving The Personality Changes on Version 2.2.5.4 Doesn't Work

### ISSUE THREAD

**Issue by Novvhere** [Solarint/SAIN#129]
I have made various changes to the personalities and every single time I click the save button after making these changes to the personalities, nothing saves despite me hitting the save button. All my other changes to a preset have stayed but not any personality change has saved at all. They just revert to what they were before I made my modifications to them. I also am playing on SPT version 3.8.3. 

Below is all of the others mods I have installed just in case it helps. 

[SAIN (Requires BIGBRAIN and Waypoints
[BIGBRAIN
[Waypoints
[That's Lit
[Virtual's Custom Quest Loader
[Scorpion (Requires VCQL)
[SAMSWAT's Helicopter Crash Sites
[Artem (Requires VCQL)
[Lotus (Requires VCQL)
[Accurate Circular Radar
[Server Value Modifier (SVM)
[Girl's Frontline Operation Novensk (Requires VCQL)
[Raid Overhaul
[The Machine (Requires VCQL)
[Peacemaker
[Backdoor Bandit
[Borkel's Realistic Night Vision Goggles
[Borkel's Big Realistic Thermal Package
[GTFO
[Borkel's Bloody Bullet Wounds
[Valens Progression
[Unheard Kukri
[Ammo Stats in Description
[Looting Bots (Requires BIGBRAIN)
[Questing Bots (Requires BIGBRAIN)
[SWAG + DONUTS Dynamic Spawn Waves and Custom Spawn Points (Requires Waypoints)
[Fontaine's Red Dot Tweaker
[Open Extract
[Live Flea Prices
[Boss Notifier
[Armsel Striker- 12
[Beretta 93 Raffica
[No Grenade ESP
[EFT API
[Day Time Cultists
[PMCs Have EOD Account
[Politely Remove Beta
[SAMSWAT's Fire Support - Arys' Reloaded
[Live Bitcoin Prices
[Item Context Menu Extended
[Magazine Inspector]
[Hultafors Dead Blow Hammer
[Painter Trader
[Tactical Gear Component (Requires Painter)
[Sandcore (Requires Painter)
[Blackcore (Requires Painter)
[Whitecore (Requires Painter)
[Greencore (Requires Painter)
[Mag Tape (Requires Painter)
[Redcore (Requires Painter)
[Trader Scrolling
[The Blacklist - Flea Market Enhancements
[IMI Uzi Submachinegun
[De-Clutterer
[UI Fixes
[Geneburn Music Pack
[HandsAreNotBusy
[Seasonal Weather at Home
[LootValue
[MoreCheckmarks
[Medical SICC Case (MICC)
[Game Panel Hud (Requires EFT-API
[Use Loose Loot
[Callsign
[Color Converter API
[Search Open Containers
[Freecam
[Stash Search
[Pause
[Modding Stats Helper
[Quick Move To Containers
[Rai's Hidden Stashes
[Player Encumbrance Bar
[Level Rewards
[Sasha Himik Trader (Requires ACAI & VCQL)
[Arys' Custom Asset Importer
[Custom Launcher Backgrounds
[Inventory Organizing Features
[Healing Autocancel
[SPT Profile Editor
[BetterMeds Revised
[Door Randomizer
[Pity Loot
[Custom Interactions
[BrightLasers

**Comment by AnikusStag** [comment]
Can confirm, since i updated the second to last patch. It creats a new profile so it seems like changes are saved and as far as i can tell it saves it for the time being, but once i restart the game the changes are gone/reset even tho the profile is still there, but its only default settings

**Comment by Solarint** [comment]
Yeah its a bug. I made an oopsie and its looking for the wrong folder name. The pre-release build currently up in releases has it fixed.

**Comment by Novvhere** [comment]
> Yeah its a bug. I made an oopsie and its looking for the wrong folder name. The pre-release build currently up in releases has it fixed.

Awesome. God bless.

**Comment by Viic420** [comment]
Sorry for my English as this is a Google translation.

I have experienced this problem and it is something that persists, since I have tried to add the files from previous versions of personality directly to the SAIN folder and still, when you restart the game, or simply close and open F6, the default values ​​​​continue to appear. 
I thought it might be an incompatibility when exporting my previous settings to this new version, but it is not. I imagine it must be a bug. We await news, thank you for the good work, ignoring the inevitable errors, greetings.

**Comment by 0pachki** [comment]
To fix this temporarily, I had set the SelectedDefaultPreset and DefaultPreset to my custom one in the config, but it was disabling the F6 menu so I had to continue editing personalities using the actual .json files. Glad to see it got fixed I thought something was wrong with my modlist lol

**Comment by Solarint** [comment]
Fixed in an earlier version
