### ISSUE TITLE
Test Build 8.1 for SPT 3.5.7 bot doesn't move sometime.

### ISSUE THREAD

**Issue by Juliozer** [Solarint/SAIN#13]
I don't know if it's a bug or not, but sometimes I come across a bot that doesn't do anything, it just stands there and waits for death.

Questions: What is zSolarint-SAIN-ServerMod? Is it necessary? Is it a mod or an extension of BepInEx?

**Comment by ASwedishGamer** [comment]
the server mod looks like it should go into "user/mods" but im not sure and i have no idea what it does

**Comment by ASwedishGamer** [comment]
i think you should try using it i think its a support mod for the actual mod. i took a look at the code looks like a config file almost. i dont know shit about moding tho so dont trust me to well

**Comment by Yangy1319** [comment]
And sometimes the bots beam you, flick like no tommorow and know exactly where you are.

**Comment by Juliozer** [comment]
Yep sometime, the bot are "Cool" and sometime Rambo.

**Comment by Juliozer** [comment]
> And sometimes the bots beam you, flick like no tommorow and know exactly where you are.

So I tested the latest build and it was impossible to play. The bots were pre-shooting me, targeting even the tiniest pixel of my character and hitting me with laser-like precision. I reset all the settings in the F12 menu.

**Comment by Solarint** [comment]
I'm not sure what would have changed recently to cause that. I haven't
modified anything about how accurate the bots are since I released the
scatter rework in the 3.5.5 version, which is included in this mod. Bots
are actually less deadly since I nerfed the range that they can use full
auto substantially since the first test build.

**Comment by Juliozer** [comment]
Well, I tested version 10 and now the bots are completely fine, and I reset the preferences again in the F12 menu. So yeah, it's very strange. Maybe another mod is causing this issue? But the only mod that affects the bots is BetterSpawnPlus.
