### ISSUE TITLE
SAIN mod no longer works in the SIT launcher

### ISSUE THREAD

**Issue by Fax287** [Solarint/SAIN#133]
Hello there. Unfortunately I would like to make you aware that the mod no longer opens when you hit the f6 key nor does it appear in the Configuration Manager . The issue began several days ago and it is now acting up. We are playing on the EFT version of 0.14.1.3.29351. At first it showed up in the configuration manager but would freeze when I went to open the menu and would require an alt-f4 to close. I tried a fresh install of all SPT related files including the SIT Manager and that did not work and now the SAIN menu wont appear in the configuration manager. The Server was running Amands's Graphics, Big Brain, Configuration Mananger,  Looting Bots, SAIN, That's Lit, and Waypoints.

**Comment by Solarint** [comment]
As far as I know, sain does not work natively with SIT. It works fine with fika though.
