### ISSUE TITLE
HUD Bug

### ISSUE THREAD

**Issue by verty96** [Solarint/SAIN#135]
Nice work with the new update, but it seems it conflicts somehow with the lootradiusplugin, so its hudelement doesnt show up..
any idea how to fix? or is that something only drakia(lootradius) can resolve?

**Comment by Solarint** [comment]
I seriously doubt sain has anything to do with this.

**Comment by verty96** [comment]
> I seriously doubt sain has anything to do with this.

yea, the new update for questingbots has the same issue.. and some other plugins i dont remember right now.
so used to the lootradius that i dont want to play without it anymore (like SAIN <3)
guess i have to update 3.8.0->3.8.3 may thats the solution.
And when everything is how i want, 3.9 is out xD
however, thanks for the reply and for all your work/time, keep it up :)
