### ISSUE TITLE
PMC will squat and shoot when encountering players at a certain distance, which is both silly and unrealistic

### ISSUE THREAD

**Issue by Duckneck1999** [Solarint/SAIN#137]
In recent versions, when the distance between PMC and players is greater than 5 meters and less than 20 meters, they will squat and shoot when encountering players, which makes them feel very dazed

**Comment by Solarint** [comment]
I'll double check the code, because if its working as intended, they would only crouch when theres an object between them and their enemy to actually crouch behind.

**Comment by Duckneck1999** [comment]
> I'll double check the code, because if its working as intended, they would only crouch when theres an object between them and their enemy to actually crouch behind.

Thank you for your active repair. This issue only started to appear in the last two to three versions, and this strange squatting behavior is 100% triggered. I hope your future improvements and fixes can make PMC more intelligent and realistic in simulating player operations. I am willing to test any function I can for SAIN because I want it to become better

**Comment by Solarint** [comment]
This got overhauled in 3.0.0 release.
