### ISSUE TITLE
Headshot protection not covering throat?

### ISSUE THREAD

**Issue by tannenheuser** [Solarint/SAIN#138]
Similarly to how the stomach-targeting issue was reported recently, I have over the last few weeks of playing several builds of SPT and SAIN, come to the conclusion that headshot protection doesn't properly cover the throat. I keep getting one-tapped (i.e. I get shot and killed immediately by bots, with no other damage recorded than to the throat, before I have time to react). This happens 5-10 times more frequently than other headshots (with headshot protection enabled). I just get the impression that bots aiming for center mass allows them to sometimes hit the throat inadvertently. Bots in this case includes both scavs and PMCs. 

SPT 3.8.3
Mod: OpticRework version: 1.2.2 by: ACOGforlife, SAMSWAT loaded
Mod: Borkel&#39;s Bloody Bullet Wounds version: 1.0.3 by: Borkel loaded
Mod: BRNVG - N-15 Adapter version: 1.0.0 by: Borkel loaded
Mod: SPTQuestingBots version: 0.5.0 by: DanW loaded
Mod: DoorBreacher version: 1.1.5 by: Props loaded
Mod: Expanded Task Text version: 1.5.0 by: Dirtbikercj loaded
Mod: Fontaine FOV Fix &amp; Variable Optics version: 1.2.0 by: Fontaine loaded
Mod: Two Slot Extended Mags version: 1.0.3 by: Platinum loaded
Mod: custom-raid-times version: 1.6.0 by: Refringe loaded
Mod: SVM version: 1.8.3 by: GhostFenixx loaded
Mod: NoDiscardLimit version: 1.4.0 by: Skwizzy loaded
Mod: SPT Realism Mod version: 1.2.2 by: Fontaine loaded
Mod: SWAG + DONUTS version: 3.3.5 by: nooky and props loaded
Mod: SAIN version: 2.3.0 by: zSolarint loaded

**Comment by Solarint** [comment]
You can lower the height that is considered "center mass". ("Center Mass Point" under globalsettings, Aiming, with advanced options shown) But recoil and random scatter from bot's aiming will cause them to accidently aim for the head/neck area sometimes, reducing their scatter will cause them to do this less.
