### ISSUE TITLE
Bots stuck standing up after death

### ISSUE THREAD

**Issue by Elite911** [Solarint/SAIN#139]
Not sure if this is an issue by the mod but whenever an AI dies they just get stuck standing up in the position they got killed in.
Client log: 
[server-2024-06-03.log](https://github.com/user-attachments/files/15533497/server-2024-06-03.log)

**Comment by malfboi** [comment]
Try clearing user/cache for the server host, this will make your next server launch take longer and may increase load in time for any clients on the next load in as a one off, just bear with it. 

Have you had this issue on singleplayer or on FIKA? I have run into it as a client on FIKA but not SP and I think I have run into it before on MPT.

**Comment by Elite911** [comment]
I only play the SP version but I'll give clearing cache a go.

**Comment by Solarint** [comment]
Not related to SAIN
