### ISSUE TITLE
SAIN 11.3 Bots Don't Attack First

### ISSUE THREAD

**Issue by Oraceon** [Solarint/SAIN#14]
Bots seem to only shoot at you once you shoot back, otherwise, they seem to just ignore you.

**Comment by Juliozer** [comment]
Weird, SCAV or other? Because i notice that on scav but the other shoot me like crazy guy!

**Comment by Oraceon** [comment]
Scavs mostly.

**Comment by Solarint** [comment]
This is default behavior afaik, they do eventually shoot you but they hesitate, I'm not intentionally changing it, but I'll see if something I'm doing is interrupting that "hesitation process" but scavs definitely shoot at me plenty in my own testing.

**Comment by Juliozer** [comment]
Yeah, but since build 12, I've noticed fewer scavs like this.
