### ISSUE TITLE
Sain Errors

### ISSUE THREAD

**Issue by Raaagincajun** [Solarint/SAIN#142]
SPT Version: 3.8.3
Mods: 
SAIN
FIKA
LootingBots
BetterspawnsPlus
BigBrain
Waypoints

Since the newest update I'm receiving lots of SAIN errors saying that PMC's have loaded with the incorrect brain type and that either a mod is overwriting the setting or the mod is installed incorrectly. The errors are great to be able to see them, however I don't understand what could be generating them? I only have a few mods, almost all list SAIN as a recommended and compatible mod, and the install process is just to extract to my SPT root folder, which I've done.

Thanks all,

**Comment by Solarint** [comment]
better spawns plus causes it.

**Comment by Raaagincajun** [comment]
I didn't know that mod touched bot behavior, good to know, thank you! Is there a way to configure Better Spawns plus to behave with SAIN or should I switch to SWAG + DONUTS ?

**Comment by Raaagincajun** [comment]
I currently have SAIN at the bottom of my load order, with BetterSpawnsPlus at the top of the load order. I'm still receiving errors, any other advice?

**Comment by Raaagincajun** [comment]
Update: I have removed better spawns plus, and am still receiving errors
