### ISSUE TITLE
Bots stuck on doors

### ISSUE THREAD

**Issue by Thecrunchyderp** [Solarint/SAIN#143]
Whenever I do a factory raid, I always find 2 bots continuously walking into the two doors of the office. While they are stuck, they don't react to me regardless of if they are scav or pmc. I'd also like to mention that they stuck bots can be scav and pmc and they do not react to each other at all.

SPT v3.8.3
Mods:
Questing bots
FOV fix
SWAG + Donuts
SVM
The Blacklist
Backdoor Bandit
SAIN
Big Brain
Waypoints
That's Lit

**Comment by Solarint** [comment]
Should be a lot better in 3.0.0 release
