### ISSUE TITLE
having issues with install 

### ISSUE THREAD

**Issue by Sfly315** [Solarint/SAIN#144]
i did everything exactly as showed in the videos . Launcher recognizes that sain is on there but nothing shows in f12 and nothing happens when i hit f6 . i only have fika sain waypoints and bigbrain installed . im not seeing any kind of error messages and ive deleted and reinstall the 3 mods a few times to see if i did something wrong

**Comment by Sfly315** [comment]
also im running the lastest versions of everything

**Comment by malfboi** [comment]
Inside the SAIN download there are 3 folders: BepInEx, optional, user. Make sure that BepInEx and user are pasted into your SPT root directory. You should have a folder called `zSolarint-SAIN-ServerMod` in your `SPT/user/mods` folder and a folder called SAIN in SPT/BepInEx/plugins

**Comment by Sfly315** [comment]
I did that and that folder is also in the mods folder
Sent from my iPhone

On Jun 9, 2024, at 3:08 PM, Barnaby Hughes ***@***.***> wrote:

﻿

Inside the SAIN download there are 3 folders: BepInEx, optional, user. Make sure that BepInEx and user are pasted into your SPT root directory. You should have a folder called zSolarint-SAIN-ServerMod in your SPT/user/mods folder and a folder called SAIN in SPT/BepInEx/plugins

**Comment by malfboi** [comment]
Can you upload what your user/mods and SPT/BepInEx directories look like
