### ISSUE TITLE
Bot never use their grenade.

### ISSUE THREAD

**Issue by LINGINOA** [Solarint/SAIN#145]
Completely reinstall the sain2.3.3 bigbrain0.4.0 and waypoint 1.4.3

With mods(Fika,Questing Bot,Looting Bot,,SWAG+Dounts)

Bot never use their grenade since i update.
Tried various difficulty presets.

**Comment by Duckneck1999** [comment]
me to

**Comment by Nemesir** [comment]
me too the same mod as yours

**Comment by malfboi** [comment]
Have you definitely got the bots enabled to throw greandes on their personality settings? First check `F6 -> Home -> Global Settings -> General -> Bot Grenades` 
Then check your bot settings `F6 -> Bot Settings -> PMCs -> Select USEC & Bear -> Select the difficulty -> Bot Grenade Settings`  

If you are confused about the difficulties they work like this: Easy, Normal, Hard, and Impossible are the diffculty options. The diffculty AIs spawn with is set in `Donuts -> Donuts PMC Spawn Difficulty` . You can fine tune these difficulties in the SAIN F6 menu

**Comment by I-Svanidze** [comment]
It appears that the "Bot Grenades" setting is set to "True" by default, but in the specific bot settings, the "Can Throw at Visible Enemies" is disabled for every bot type at every difficulty.

**Comment by LINGINOA** [comment]
> It appears that the "Bot Grenades" setting is set to "True" by default, but in the specific bot settings, the "Can Throw at Visible Enemies" is disabled for every bot type at every difficulty.

tried it but helpless

**Comment by I-Svanidze** [comment]
Bots most certainly use their grenades, since there are quite frequent explosions during most raids and many corpses I loot usually have at least a couple. However, just like you, I haven't had a bot throw a grenade at me yet. Somewhat funny proof of a bot using a grenade:
![image](https://github.com/Solarint/SAIN/assets/111082952/0ecdd6fe-a365-4d09-b67a-ff5106fdc418)

**Comment by TapsGG** [comment]
I have exactly the same "issue" i can here some times VERY RARE granades in my raids but i have like 130hrs with SPT and SAIN and i never had a bot throw a granade and they have granades on them. i have double checked all the settings for granades i tried many dif variations of settings and i never had a bot throw a granade at me.

**Comment by Solarint** [comment]
Fixed in 3.0.0 release
