### ISSUE TITLE
DUMB SCAVS AND DIFFICULTY

### ISSUE THREAD

**Issue by Viic420** [Solarint/SAIN#147]
Hello everyone. 

Lately I have experienced that the scavs are really stupid, when I play PMC there are some that despite standing in front of them at 2 meters, or even accompanying them on their route, they do not appear hostile and shoot at my pmc.

Then, I get the feeling that the difficulty is considerably reduced. I use the highest difficulty setting, even making it more difficult, and even so I still find the raids very easy. Am I the only one who has experienced these things? 

Thank you, good day

**Comment by malfboi** [comment]
Is SAIN enabled for Vanilla Scavs? Check `F6 -> Sain Enabled For Bot Types` 

You can fine tune difficulty under `F6 -> Bot Settings -> Scavs -> Scav -> Difficulty`

**Comment by Viic420** [comment]
Yes I use the vanilla scavs configuration. I'm going to try disabling the option. The problem is as if they were blind. Maybe a bug? I will try to regulate their personalities based on the other personality options. Also yesterday I installed version 2.2.4.01 and it seems that the problem persists. I also attach a list of my mods in case it was a problem with another mod and I was wrong.

Thanks

![image](https://github.com/Solarint/SAIN/assets/171266575/005cd149-00ba-431f-ad8f-e707cd0bec4f)

**Comment by Solarint** [comment]
If you use vanilla scavs...they are going to be vanilla. That means no personality, nothing. Nothing you change in sain's gui will affect them.
