### ISSUE TITLE
Request for additional method in `External.cs` - GetBotComponent(string botGuid) 

### ISSUE THREAD

**Issue by christopher-talke** [Solarint/SAIN#151]
Hello 👋🏾

Working on extending the mod Raid Review to pull some info from SAIN (if it's installed), and we're trying to access properties in the component `BotComponent` attached to an instance of `Player`.

Right now, are accessing this via `player.gameObject.GetComponent<BotComponent>();`

Would it be at all possible to implement a method like `GetBotComponent(string botGuidId) { ... }` that returns that?

**Comment by Solarint** [comment]
I believe i added what you were looking for, let me know if you need something else.

**Comment by christopher-talke** [comment]
Legend, thanks mate @Solarint
