### ISSUE TITLE
Change Bot Reaction of Grenade (not an Issue just a question)..

### ISSUE THREAD

**Issue by Littlelucy99** [Solarint/SAIN#152]
I was asking in SPT DC for your mod if it possible to re-enable the grenade reaction like in eft like.. that they give a reaction to them without seeing your grenade directly.. I enabled vanilla talking which had not any effect to this.. is there a way to change that behaviour ?

Greetings.

**Comment by Solarint** [comment]
Not going to happen, sorry.
