### ISSUE TITLE
Enhancement suggestion for "speedhacker spawn chance" option

### ISSUE THREAD

**Issue by kakahost** [Solarint/SAIN#153]
Rename it to "cheaters spawn chance" option, add ability to adjust this chance and add HECS (SBEU) Komar/Mosquito and HECS Worm. That would feel like real Tarkov.
 For ones who wanna feel full Tarkov experience add "hardcore mode" option which would spawn cheaters which can steal items from your backpack or gun. (I didn't play live Tarkov for 8 months, I don't know much about situation with cheaters). That would be very cool.

**Comment by kakahost** [comment]
I'm reading it 2 hours ago - sounds like schizophrenia.

**Comment by Solarint** [comment]
Done

**Comment by kakahost** [comment]
I could not belive that you would do this
