### ISSUE TITLE
SAIN PMC issues.

### ISSUE THREAD

**Issue by DukeOfGhost** [Solarint/SAIN#155]
I've seen the previous post about this, and I am not running "Better Spawns Plus", advice?
![PXL_20240701_200359450](https://github.com/Solarint/SAIN/assets/174381773/265373ea-c6b2-469c-85c8-72d41da3c402)
![Capture](https://github.com/Solarint/SAIN/assets/174381773/b727fe6c-bdf8-4496-be09-c87dea4fab7d)
![Capture2](https://github.com/Solarint/SAIN/assets/174381773/f1cde3a7-f5fa-4cad-9b7b-0ef080fc0e86)

**Comment by Solarint** [comment]
Sit is not compatible
