### ISSUE TITLE
Detecting Tojan in download from hub

### ISSUE THREAD

**Issue by Sheersy** [Solarint/SAIN#157]
![image](https://github.com/Solarint/SAIN/assets/175047335/9b0030c3-58a9-4640-993b-abf86d1c33b4)
see image ^^ 
Windows defended is detecting a trojan and blocking download - didnt have this issue when downloading previous version :)

**Comment by Solarint** [comment]
Its a common false positive, its always Wacatac. I can assure you its clean, theres a virus total result on the hub page.

**Comment by Sheersy** [comment]
Dont know if you changed something - but download worked perfectly today
