### ISSUE TITLE
Bots appear to get stuck in bushes - Sain 3.0.0, SPT 3.8.3

### ISSUE THREAD

**Issue by TheRaven15** [Solarint/SAIN#159]
Thru direct and passive observation (utilizing the Raid Review mod), it appears that bots get stuck when encountering bushes.  Have observed this happening in multiple raids now.

Sain version: 3.0.0

SPT version: 3.8.3

Mod List:

All the Clothes; Amand's Graphics; Artem; Backdoor Bandit; Better Keys; BigBrain; Black Core; Custom Quest Loader; Dynamic Maps; EFT API; Epic's All in One; Expanded Door Interactions; Fontaine's Red Dot Tweaker; FOV Fix & Variable Optics; Game Panel Hud; Helicopter Crash Sites; Increased FOV; Item Info; Trader Scrolling; Server Value Mod; Load Order Editor; Looting Bots; Mag Tape; MFAC Shop; Modding Stats Helper; Modular Attachments; Painter; Player Encumbrance Bar; Questing Bots; Quest Tracker; Raid Review; Fika; Realism Compatibility Patch; Realism Mod; Realism Stance - Fika Compatibility; SAIN; Skipper; Realistic Night Vision Goggles; Stackable Grenades; SWAG + Donuts; Tactical Gear Component; Task List Fixes; Realistic Thermal Package; Trader Modding & Improved Weapon Building; UI Fixes;  Waypoints;  

I have a recent Raid Review log that appears to show a cluster of 5 bots initially being able to navigate the map, but when approaching what appears to be bushes they get stuck.  I'm not sure if/how I could possibly share this (I don't believe the mod allows this quite yet) but will keep it around just in case.

I don't have the limiters enabled for Looting or Questing bots.  And from watching the Raid Review, there is a bot around the frozen-five that appears to be looting/questing just fine.  

BepInEx logs attached.  If it helps - the most recent raid I played is when I encountered the frozen-five.  I hope that is reflected in the attached log files.

Let me know if you need any info, or if you want my Raid Review log.  

Incredible work - I'm having so much fun!!!!

[FullLogOutput.log](https://github.com/user-attachments/files/16149490/FullLogOutput.log)
[LogOutput.log](https://github.com/user-attachments/files/16149491/LogOutput.log)

**Comment by Solarint** [comment]
Never been able to witness this
