### ISSUE TITLE
Bot behavior!

### ISSUE THREAD

**Issue by HeavyComponent** [Solarint/SAIN#162]
Bots seem to be stuck in one spot and just be peaking and never move.  They know where the enemy is but nobody makes a move. They keep peaking in the direction the enemy is in and take cover. 

I'm currently on 3.9.0 SPT.

On 3.8.3 bots move flawlessly, at least in my experience.

Edit: Another thing I notice is Blood Hounds group up in one spot and never move. I’m not sure if they supposed to but I remember in 3.8.3 I saw them walk the map.

**Comment by ForeskinJohn** [comment]
to iterate further on this, its almost as if the bots are strafing to avoid being hit, and its super annoying, makes them impossible to hit, while they remain on target, and there isnt an option to disable this, if its a feature.
