### ISSUE TITLE
SCAVS and grenades

### ISSUE THREAD

**Issue by Luxyno** [Solarint/SAIN#163]
Hey, i just want to say that SCAV throwing all grenades at once. :) Its quite a barrage sometimes when four grenades explode at once.

**Comment by MobyDukke** [comment]
I have this problem to. For now, i just disable de ability to AIs to use grenades. I'm using SAIN and Fika, no other mod that changes the AIs intelligence logic.

**Comment by Solarint** [comment]
Should be fixed now in 3.1+
