### ISSUE TITLE
Goons and Ai PMC

### ISSUE THREAD

**Issue by Luxyno** [Solarint/SAIN#164]
Seems like Goons are friendly with Ai PMCs.

**Comment by LCJST** [comment]
Also, PMC's and SCAVs are not killing each other.

**Comment by AfxousaAjagara** [comment]
me too, I also experience this problem. PMC's and SCAVs never fight each other, but I watch Killa killing PMCs. 
I don't know what cause this inconsistency.

**Comment by igor0000000** [comment]
Yep, PMC's and Bosses don't see each other. Sometimes it's happened with PMCs and SCAVs.
Bosses(Kolontay F.E.) and Supports don't attack the player

**Comment by fourhundred-KG** [comment]
Same issues w/ newest release. Scavs/PMCs and bosses hardly fight each other. If at all. I watched it w/ Dynamic maps as they stood by each other not even acting like they were enemies
