### ISSUE TITLE
Scav does not attack players

### ISSUE THREAD

**Issue by Duckneck1999** [Solarint/SAIN#167]
When I set Vanilla Scavs to ON in the Vanilla Bot Behavior Settings in General, the SCAVs patrolling in the game will not notice or attack me, but the sniper SCAV is functioning normally. My SPT version is 3.9.1, I want to know if this is a bug or a problem with my configuration?

**Comment by kakahost** [comment]
This is a bug. The same happens with everyone. I deleted SAIN because it makes game feel dead and broken in it's current state. Let's wait for an update.

**Comment by Duckneck1999** [comment]
> 这是一个错误。每个人都会遇到同样的情况。我删除了 SAIN，因为它让游戏在当前状态下感觉死气沉沉。让我们等待更新。

This is a very serious bug, I hope it can be fixed as soon as possible
