### ISSUE TITLE
Bots stuck in "Holding cover" for absurd time and refusing to fight each other. 

### ISSUE THREAD

**Issue by WhiteRaven47** [Solarint/SAIN#168]
Playing on 3.9.0 and 3.9.1 with the latest SAIN. Bots appear be on "Hold Cover" for unreasonable amount of time. This happens if they hear a bush sound or fire that isn't even close or aimed at them. For 2+ minutes they won't move. I've tested this with AI debugger on so I can track their state. Affects all NPCs , scavs, PMCs , player scavs, except the bosses which behave as normal. 

Furthermore, AI PMCs and Scavs don't actually fight. Several times I am watching them be literally in front of each other , 5 meters away and they won't engage like they don't seem to notice each other. 

This leads to raids that even with 25+ AIs active feel absolutely dead, as the player is the only one shooting and engaging AI. 

On factory for example it's absurd, AI will rarely engage each other and will just sit in cover or behind a corner and won't move for half the raid.

**Comment by Duolol1** [comment]
Happening to me too, the AI will just walk past each other and not do anything or just sit there and stare at each other.

**Comment by kakahost** [comment]
Solariant fixed one critical bug and created another one) God damn this SPT 3.9.0.

**Comment by ILikeHotdogs00** [comment]
This is still happening on version 3.1.0 on SPT 3.9.5.
