### ISSUE TITLE
Error Sain Logger system string...

### ISSUE THREAD

**Issue by sk1zog4m3r** [Solarint/SAIN#169]
I captured the error

https://i.ibb.co/hVzzphz/BUG2.jpg

mods used in SPT 3.9.1: 
Sain + BigBrain + Waypoints

c.u

edit:
the error was in Factory, no error appear in Ground Zero

**Comment by HeavyComponent** [comment]
I got the same error in Customs. It pops up for different bots. I'm glad I wasn't the only one with this.

**Comment by Solarint** [comment]
Look like another mod is overwriting sain's server mod or sain server is mod is missing entirely.

**Comment by lukaskabc** [comment]
> Look like another mod is overwriting sain's server mod or sain server is mod is missing entirely.

Playing with FIKA, I have installed BigBrain, Waypoints, SAIN, and looting bots (the errors occurred even before the installation of looting bots)
Headshot Damage Redirect and ADS Volume Adjuster from the optional folder from the SAIN archive
no other mods are installed 

BepInEx / [LogOutput.log](https://github.com/user-attachments/files/16459888/LogOutput.log)

in `user/mods/order.json`, I have
```json
{
    "order": [
        "Skwizzy-LootingBots-ServerMod",
        "zSolarint-SAIN-ServerMod"
    ]
}
```
