### ISSUE TITLE
Custom profile not saving 

### ISSUE THREAD

**Issue by PorkChopxpres** [Solarint/SAIN#172]
Hello, love the mod btw and all the effort and time you've put into this project.  I'm running spt version 3.9.2 (problem happening on 3.9.1 too) and the latest version of your mod.  As mentioned above when i make a custom profile (using one of the presets as a base) it is not loading when i launch the game, i have to go into a raid and alter all my changes from there each time i first play the game.  Everything from difficulty of each type of AI to hearing settings etc. I press save and save & export but nothing seems to fix this.

Mods.....
big brain 
waypoints
donuts
dynamic maps
sain
morecheck marks

thanks again and look forward to your response, probably be something on my end lol

**Comment by BonelessPoop** [comment]
I wouldnt say its on your end because I have the same exact issue. Seems like SAIN is the only issue im having in terms of mod loading. I tried turning baby bots on and it feels like PMC terminators, yet i dont have the terminator mods installed lol hoping this gets solved soon.... 3.9.2 feels amazing aside from getting one shotted.

**Comment by PorkChopxpres** [comment]
I noticed that when I loaded into raid the setting you have chosen for the difficulty on the bot settings is unchecked.  So load into raid find a hiding spot, F6 and then select bot setting.  This will then stay on until you finish playing for the day.

**Comment by PorkChopxpres** [comment]
Change hearing and global scatter bars too.  These settings will stay adjusted, it's just the bot difficulty that needs amending first raid of the day.  Save and export then save all changes

**Comment by BonelessPoop** [comment]
ill look into that later on, appreciate it!

**Comment by PorkChopxpres** [comment]
No problem, and with the recent update to sain you can now do the bot settings pre raid

**Comment by Solarint** [comment]
Any issues must include a full list of your server and client mods, the version of SPT you are playing on, and either your Bepinex/LogOutput file or an exact description of the issue you are experiencing and the context of when it occurred. Just telling me "its broken" is not helpful what so ever.

**Comment by PorkChopxpres** [comment]
I have listed all that on the first comment!!

**Comment by PorkChopxpres** [comment]
> Hello, love the mod btw and all the effort and time you've put into this project. I'm running spt version 3.9.2 (problem happening on 3.9.1 too) and the latest version of your mod. As mentioned above when i make a custom profile (using one of the presets as a base) it is not loading when i launch the game, i have to go into a raid and alter all my changes from there each time i first play the game. Everything from difficulty of each type of AI to hearing settings etc. I press save and save & export but nothing seems to fix this.
> 
> Mods..... big brain waypoints donuts dynamic maps sain morecheck marks
> 
> thanks again and look forward to your response, probably be something on my end lol

**Comment by PorkChopxpres** [comment]
That was dated 2 weeks ago just for reference

**Comment by Solarint** [comment]
I have no idea what the issue is describing. Try sain 3.1 and see if the issue persists.
