### ISSUE TITLE
Stuck on loading loop

### ISSUE THREAD

**Issue by Vytis80** [Solarint/SAIN#173]
Hello,

i'm asking for help because every time I install SAIN with all the other required mods it just gets stuck on loading loop, but when i delete it everything just works fine.
SPT 3.9.0
Ask me what aditional information is required and I will provide it.
Here is all the mods that i have installed:
![Modss](https://github.com/user-attachments/assets/bcfab5f8-52ef-4bd3-b3c6-412bf9d3edc8)
![pluginss](https://github.com/user-attachments/assets/93d04c62-2c25-4062-9d95-7d481ae633a7)

**Comment by FedericoRocca** [comment]
Exactly the same problem here

**Comment by Solarint** [comment]
This is not a support channel
