### ISSUE TITLE
WITH realism mod, SAIN does not working on player scav when turn vanila scavs bot option on

### ISSUE THREAD

**Issue by 0bey1k** [Solarint/SAIN#174]
thanks for your work.

with realism mod 1.4.0, vanilla scav bot behavior option also affects on pscav(unlike that option's description).

realism's bot changing option making this situation.

tested on new fresh install SPT 3.9.2 with only SAIN 3.0.5, Realism 1.4.0.

**Comment by Solarint** [comment]
I cannot change realism from changing how "player scavs" are handled.
