### ISSUE TITLE
SAIN Difficulty wont adjust

### ISSUE THREAD

**Issue by BonelessPoop** [Solarint/SAIN#175]
When trying to switch to baby bots, it seems to stay at a higher difficulty such as default. I keep getting one shotted with baby bots saved and enabled.

**Comment by IronMaiden7707** [comment]
Yeah, the difficulty in 3.0.5 is insane, bots reactions are instant, SCAV's can easily wipe you, not to mention PMC's who nuke you even faster than in old SPT 3.8.3 before armor was even buffed. I haven't noticed any difficulty change with easier presets. 

Also, most bots sit or lay down in the corners and wait for you (spots are almost the same as far as I noticed), sometimes even in packs of 2-3.

Bots in 3.8.3 were amazing, human-like reactions, accuracy, and spotting. Now it's like fighting "Goons", bots always know where you are, aiming exactly at your position and zerging you. I had like 10 dead bodies in a couple of minutes who rushed me on Factory map.

P.S A couple hours ago was lazer beamed by bot PMC lvl3 with fully stock AKM without any mods from 40-60 meters. Level 6 plates destroyed, limbs and stomach are black, and a bunch of bleeds. Reaction time and accuracy are crazy. In some cases bots can stand near you and do nothing like they don't see you at all.

**Comment by StyxxeD** [comment]
I'm getting the same experience. Even with the grenade spam fix, bots still laser and nade you from the most impossible angles in the blink of an eye.

**Comment by BonelessPoop** [comment]
I took out SAIN, Waypoints, and Swag+Donuts to see if that fixed the bots. Sure enough, that didnt do much. So I went into SVM and adjusted my PMC health by setting each limb at 500hp. Even if the bots laser me, I can still have a fighting chance at fighting back. I just make sure to pack a grizzly or two lol Without those 3 mods, and with pack-a-punched health points, it literally feels like SAIN, but they cant one shot me now. So something tells me its with the base update of the game that has cranked the bots to terminator difficulty. The bots do try to congregate around where they hear shots being fired at, for example, if Im at gas station on customs and fighting a PMC squad, a good 5-10 scavs and some PMC bots will show up. Maybe a bit more bots show up than id like, but its what we have to work with for now. So for now, I just try to eliminate who I can, loot what I can, and then i dip out ASAP lol I forgot to mention that I set the SVM value of the bots difficulty to easy, and the amount of them to low. Its the closest thing Ive gotten to having a fair fight and it seems to work for now. Im not getting one shotted anymore, but they can light me up pretty good. So I highly recommend these settings within the SVM until SAIN or Waypoints/SWAG gets fixed....

Server Value Modifier Settings:
(Player and Skills) - Player Health = Each limb set to 500
(Raid Settings) - Raid Startup Settings = Difficulty of Bots [Easy], & Amount of Bots [Low]

Delete SAIN, Waypoints, and SWAG+Donuts, but KEEP BIG BRAIN, QUESTING BOTS, AND LOOTING BOTS

Overall, this should suffice for now. I hope this helps!

**Comment by Solarint** [comment]
If its too hard, get a different mod to make the game easier by giving yourself more health. Or watch videos on how Tarkov is played 🤷‍♂️

**Comment by BonelessPoop** [comment]
i know how tarkov is played, i have hundreds of hours lol its the bots that are the problem, not me. but thanks anyway for the 'tude bud

**Comment by Manucrux** [comment]
> Sí, la dificultad en 3.0.5 es una locura, las reacciones de los bots son instantáneas, los vehículos blindados pueden aniquilarte fácilmente, sin mencionar a los PMC que te bombardean incluso más rápido que en el antiguo SPT 3.8.3, antes de que se mejorara la armadura. No he notado ningún cambio en la dificultad con los ajustes preestablecidos más fáciles.
> 
> Además, la mayoría de los robots se sientan o se acuestan en las esquinas y te esperan (los lugares son casi los mismos hasta donde noté), a veces incluso en grupos de 2 o 3.
> 
> Los bots en 3.8.3 eran increíbles, con reacciones, precisión y detección similares a las de los humanos. Ahora es como luchar contra "matones", los bots siempre saben dónde estás, apuntan exactamente a tu posición y te atacan con un zerg. En un par de minutos, tuve como 10 cadáveres que se me echaron encima en el mapa Factory.
> 
> PD: Hace un par de horas, un robot PMC de nivel 3 con un AKM completamente de fábrica y sin ninguna modificación me disparó con un rayo láser desde 40 a 60 metros. Las placas de nivel 6 quedaron destruidas, las extremidades y el estómago quedaron negros y sangraron un montón. El tiempo de reacción y la precisión son increíbles. En algunos casos, los robots pueden pararse cerca de ti y no hacer nada, como si no te vieran en absoluto.

I have the same problem, the bots jump a corner and shoot me in the head, they shoot me at more than 200m and the worst thing is that they come for me all at once. In 3.8.3 were perfect, I have about 3000h played tarkov, a wipe I played only DVL and killed more than 400 player only DVL (I think I know how to play), I do not understand the attitude of solarint, I appreciate muchisimo his work game spt as a result of his mod, I like more than the original game, I hope you can fix this, because nikita every time the caga more.
