### ISSUE TITLE
Bots still have *hands are busy* after throwing grenades (3.9.0)

### ISSUE THREAD

**Issue by Light-of-the-World** [Solarint/SAIN#176]
The _first_ bot that threw a grenade got the "hands are busy" bug. I am on 3.9.0 but I have installed the latest SAIN, BigBrain, and Waypoints, and I don't believe I have any other mods that modify bot behavior except lootingbots (mod / plugin list included)
![Screenshot (1408)](https://github.com/user-attachments/assets/765ded44-84f6-400e-923f-a3b4424b8866)
![Screenshot 2024-07-20 124931](https://github.com/user-attachments/assets/2afb17ce-b1a2-43aa-a2c7-8fe2b97a5d59)
![Screenshot 2024-07-20 124943](https://github.com/user-attachments/assets/8c178b11-59e7-415c-a1df-b0e8b2ea32a8)
[FullLogOutput.log](https://github.com/user-attachments/files/16321870/FullLogOutput.log)
[LogOutput.log](https://github.com/user-attachments/files/16321871/LogOutput.log)

Hopefully I've attached everything needed

**Comment by Solarint** [comment]
It really feels like its just a dice-roll whether it happens or not, I'm trying to find ways to reduce it from happening, but its still completely unknown what actually causes this for bots, so I'm basically just guessing.

**Comment by Solarint** [comment]
At the end of the day, its a BSG bug, and I may never be able to fully fix it

**Comment by Solarint** [comment]
Should be less often now in sain 3.1+
