### ISSUE TITLE
Sain and Waypoints and Bigbrain all installed, Ai doesnt change 

### ISSUE THREAD

**Issue by Colin01234** [Solarint/SAIN#177]
I have the latest version of all three installed and I still cant get the bots to change, they act the same and are still lower than the minimum level I selected them to be, they are also all normal and there are no giga chads spawning.

**Comment by Manucrux** [comment]
Yo tambien tengo un problema, los bosses y demas bots cargan contra mi a lo largo de todo el mapa, me acorralan y vienen uno tras otro incluso cuando no hago ruido. Me ven y disparan a mas de 400 metros.

Tengo instalados aparte de sain, server value modifier, speedloader and amands graphics.

**Comment by Solarint** [comment]
This is not a support channel
