### ISSUE TITLE
Bots charge at me from all over the map.

### ISSUE THREAD

**Issue by Manucrux** [Solarint/SAIN#178]
I also have a problem, bosses and other bots charge at me all over the map, they corner me and come one after another even when I don't make noise. They see me and shoot from 400 meters away. I have the default options of the mod, I have not touched anything and it happens to me even lowering the difficulty, in 3.8.3 everything was perfect.

I have installed apart from sain, server value modifier, speedloader and amands graphics. i play in 3.9.3
[LogOutput.log](https://github.com/user-attachments/files/16325910/LogOutput.log)

Please help me, i love this mod, in 3.8.3 the ai was perfect.

**Comment by PharaoML** [comment]
same for me

**Comment by Solarint** [comment]
Bot hearing is bugged in the release version because BSG trolled me. Check the pre-releases for SAIN here on github.
