### ISSUE TITLE
f6 doing nothing

### ISSUE THREAD

**Issue by TheThannos** [Solarint/SAIN#180]
hi all. 
Sain, waypoints and big brain installed. along with SVM and more checkmarks. Pressing f6 doesnt bring up the interface.

**Comment by TheThannos** [comment]
![image](https://github.com/user-attachments/assets/1f64b85b-63f2-412f-958a-b4d4a80f14a4)
![image](https://github.com/user-attachments/assets/c714b0a0-6f33-4229-acef-15e8ffe7b273)

**Comment by vo-fr** [comment]
Check the downloaded zip file again. You are missing a folder in your 2nd screenshot.

**Comment by Solarint** [comment]
This is not a support channel
