### ISSUE TITLE
[SPT.Singleplayer] 1 plugin failed to load due to errors: Could not load [SAIN 3.0.6] because it is incompatible with: com.dvize.BushNoESP

### ISSUE THREAD

**Issue by Bravitus** [Solarint/SAIN#181]
[SPT.Singleplayer] 1 plugin failed to load due to errors:
Could not load [SAIN 3.0.6] because it is incompatible with: com.dvize.BushNoESP
![image](https://github.com/user-attachments/assets/1f605bba-6450-4355-ba42-316e6a8e95f5)

**Comment by Solarint** [comment]
Look like it failed to load because SAIN 3.0.6 is incompatible with: com.dvize.BushNoESP
