### ISSUE TITLE
Bosses/Guards are everywhere! Aggrorange is wrong?

### ISSUE THREAD

**Issue by Dizzily** [Solarint/SAIN#182]
hey we found a weird issue of bosses
dont want to post the links in public channel because of ip but i have some raid reviews showing some weird behaviour of bosses.
Thes just run all over the place and aggro over half the map. Same goes for some scavs/raiders/pmcs they are aggrod on something and run away or push over half a map. 
I have 1 RaidReview where killa was in the parking lot area and one where reshala guards take off from new gas spawn and just went to fortress/crackhouse where we killed them. Reshala stayed in same place.
One example of Reshala guards go missing:
https://www.youtube.com/watch?v=2_tGR96ro9s

We use latest Sain, Swagnuts, Waypints; Bigbrain, questing bots and looting bots.
If you want to see full raidreviews hit me up in discord @dizzily

**Comment by Solarint** [comment]
Bot hearing is bugged in the release version because BSG trolled me. Check the pre-releases for SAIN here on github.

**Comment by Manucrux** [comment]
I have seen the new version, now I will try it, thanks for your work.
