### ISSUE TITLE
Suggestion ) Add mode localization capability

### ISSUE THREAD

**Issue by GoLani11** [Solarint/SAIN#183]
Hello! I'm a user who often uses your mode. Many users also use this mode in Korea, but the mode is in English, so it's a little inconvenient to use. 
Do you have any thoughts on adding a localization function?
Of course, I know that there are difficulties in producing it, but if you make it, I think I will use it more comfortably.
And if you add a localization function, I will help you translate Korean.

Grammar can be weird because I'm a little weak in English conversation. Please understand this. And I'm sorry if it's a duplicate article.
Thank you for updating the mods frequently and thank you for reading this.

**Comment by Solarint** [comment]
I would love to do this, but it would require a large amount of work and I would have to rebuild several parts of the ui, not sure If Its something I will be able to do for SAIN, sorry :(
