### ISSUE TITLE
AI grenades

### ISSUE THREAD

**Issue by Zyhgar** [Solarint/SAIN#186]
SPT 3.9.4
SAIN 3.0.6
For some reason AI are insanely accurate with grenades at ranges of 40+ I've also noticed them throwing them at me from distances where the grenade airbursts... I feel like I am playing stalker clear sky all over again with how accurate these AI are...
Only other AI effecting mods I have is donuts, looting, that's lit and questing bots...

**Comment by Zyhgar** [comment]
![image](https://github.com/user-attachments/assets/ed018775-962a-4b4f-8e24-2fdfe432ccc0)
![image](https://github.com/user-attachments/assets/2ebe15c9-8eac-4e20-b553-190c3b7fb74e)

**Comment by Splitterbruch** [comment]
Can confirm, got some "magic" grenades thrown at me from insane distances. Even got an instance with the bot looking in a different direction, not at me. I thought the bot was throwing at another bot. Next second, I'm dead from his grenade.

**Comment by Solarint** [comment]
Grenade throws are random, and due to that sometimes they get lucky, I'll see if I can add more controls over this in the future
