### ISSUE TITLE
AI Stuck in Holdincover and won't attack eachother

### ISSUE THREAD

**Issue by ILikeHotdogs00** [Solarint/SAIN#189]
I've noticed when I look at the Questing Bots debug menu lot's of the bots usually half of them are in "SAIN CombaLayer holdincover', rarely moving only short distances and never changing from this seems like theyre stuck in this mode. It makes my raids dead. What's happening and how do I fix this?

Also notice AI don't seem to be shooting eachother. On Dynamic maps the AI that are moving (both PMC and scavs) are either moving near eachother and not shooting or bunching up and not shooting.

**Comment by Solarint** [comment]
Bots being in "hold in cover" is not a bug.
That is their default state until they make a move, the time until they do that depends on personality
If you wish to change it, the config value you are looking for is either aggression multiplier, or for exact controls, "Time Before Search" in each personality
There is a bug where sometimes bots will try to search but can't for various reasons, and I'm working on it.

As for bots not shooting each other, are you sure there isn't a vertical difference in their position on raid review? I've never actually witnessed this in actual gameplay, either way sain doesn't control who is hostile to a bot
