### ISSUE TITLE
Cannot spawn into raid

### ISSUE THREAD

**Issue by Snugglecactus** [Solarint/SAIN#191]
Server/client Mods: Waypoints, SWAG + Donuts, Unitytoolkit, BigBrain, Sain
[LogOutput.log](https://github.com/user-attachments/files/16570653/LogOutput.log)

SPT Version: 3.9.5, Fika 0.9.8983.25381
Description: I cannot load into a raid. Everything loads fine up to the point of 99% or 100% creating loot pools, then it just stops. Nothing freezes, it just won't progress any further and let me into the match. No errors appear in my server log while I sit and wait to load into the match either, it looks like it's running properly. I am not sure if this problem is caused by this mod specifically, I am just looking for help wherever I can because the discord has not responded to me, and I have not seen a fix for this issue in the discord anywhere.

**Comment by Solarint** [comment]
Not a sain issue.
