### ISSUE TITLE
Scav AI targets player behind objects

### ISSUE THREAD

**Issue by rovicomm** [Solarint/SAIN#193]
I have predominantly noticed this on Ground Zero, on the staircase with the safe in the Tarbank building, while in between levels. I have also noticed this behind rocks and cars.

I have heard a steady single shot every few seconds, which does not seem to stop as long as the scav is alive. A sound of the bullet hitting an obstacle in its path is heard. Moving from the location (a higher or lower floor) cause this behaviour to stop.

**Comment by KonstAl54** [comment]
same (311 test build)

**Comment by blockloop** [comment]
I've noticed the same. They're shooting at me from the other side of a concrete wall. There's no hole for them to see, but they are shooting anyway.

**Comment by fridgebro** [comment]
are you using LIT as well? ive been getting this with combining SAIN and LIT. lots of aiming through floors. people are saying the same thing is happening w/o having lit tho, also saying downgrading SAIN fixes it, it didnt really for me. not sure what to make of it.

**Comment by zsolczai** [comment]
Same exact thing on GZ and also on Reserve. I don't think this is map dependent. AI turns the corners already aimed at me.

**Comment by Solarint** [comment]
They will aim where they last saw you or where they last heard you. Any shots through walls is purely random from suppression.
