### ISSUE TITLE
PMC's and Pscavs taking almost 20 mins to generate

### ISSUE THREAD

**Issue by dusty8998** [Solarint/SAIN#195]
Hello, I am using your mod for the first time so I am hoping this is only a first time experience but if not I wanted to ask to see if something maybe on my end is causing this? The only mods I have installed are the exact same that you recommended and the ones that are required for it to operate. The in game timer is actually currently at 23:34 and the Pscavs are still only 48% done generating. PMC's took a very long time as well. Is this normal?

1. SAIN (obviously)
2. Big Brain
3. Waypoints
4. Looting bots
5. Questing bots

**Comment by Solarint** [comment]
Sain does not change anything related to bot spawns.
