### ISSUE TITLE
AI PMC and Bots are generated in closed quarters 

### ISSUE THREAD

**Issue by Torregroza** [Solarint/SAIN#196]
SAIN Version 3.0.6
Drakia BigBrain 1.0.1
Drakia Waypoints 1.5.1

Issue: some of the AI Bots Scavs and PMCs are generated too close to the PMC sometimes even when you have already cleared the areas, and sometimes you have just passed and reviewed that there is nothing nearby and suddenly some random AI appears.

**Comment by Solarint** [comment]
Sain does not change anything related to bot spawns.
