### ISSUE TITLE
Difficulty Issues

### ISSUE THREAD

**Issue by HoobyPoobyKanooby** [Solarint/SAIN#197]
Hello,  i recently updated from 2.2.4 to 3.0.0 and then 3.0.3 (still on SPT 3.8) and i immediately noticed all enemies being extremely slow to spot me, take aim and then shoot me. they also shoot me at a way lower firerate and seem just sluggish and very easy to fight. in the 2.2.4 version there was a global difficulty slider that i had at 3.0 and im wondering if all the parameters that the global slider affected can still be changed? ive cranked all the accuracy and spread and vision sliders for difficulty but it doesnt seem to do as much as that global difficulty slider did ?

**Comment by Solarint** [comment]
The settings in the Difficulty tab in Global Settings are what were previously changed by global difficulty.
