### ISSUE TITLE
AI agroing from well over 200m after firing a suppressed shot. AI also immediately turning to shoot at me if I miss the shot at over 200m.

### ISSUE THREAD

**Issue by DemonHunter58** [Solarint/SAIN#201]
![image_2024-09-08_115539338](https://github.com/user-attachments/assets/d3a7030c-f4c4-4437-ad43-2e308f82a2e3)
![image_2024-09-08_115557258](https://github.com/user-attachments/assets/df94023e-a68f-43b5-b77d-fe408f0a9bde)
![image_2024-09-08_115614188](https://github.com/user-attachments/assets/135250f2-fab1-4b35-bb9b-2fdccb63f8a8)

First image is my bepinx and second are my mods. I have been in multiple engagements with AI where I will shoot at them from range and they will immediately turn and shoot at me if I miss. They themselves and whatever ai they were fighting will deagro from each other and immediately try to kill me. Ai that weren't in the fight will come across the map to try and kill me already knowing my position no matter the faction. This will happen at night when the ai don't have night vision. Do I have a mod that is causing these issues? I have had the same issue with base SAIN settings, a preset someone gave me on reddit, and the Realistic Combat Overhaul preset on the website.

**Comment by jonjetjon** [comment]
i can confirm this and have videos of ai outside of their vision range instantly aiming at my head(using the aim debug gizmos to check) after a single surpressed shot beyond the hearing range of the gun when i was trying to debug, i have gone through every setting in the ai presets and can't find any tweak that makes this less of a problem. https://cdn.discordapp.com/attachments/1202824837291188244/1292662456971431977/EscapeFromTarkov_2024-10-06_19-35-52.mp4?ex=6722dfba&is=67218e3a&hm=9e8559b9231b76dc50847968af34bf29507b7508212abc8b42778bfc2d90d395&

**Comment by jonjetjon** [comment]
in the current state(whether it's intended or a bug) lighthouse is completely unplayable because you cannot shoot more than one shot without having fire returned at you and clearing the rogue camp takes almost 20 minutes from range because you have to reposition every shot even with silenced tx15 at 300+ meters

**Comment by Solarint** [comment]
Can be configured in 3.2.1+
