### ISSUE TITLE
[ FEATURE REQUEST ] Please, write full documentation about parameters in SAIN

### ISSUE THREAD

**Issue by gzhegow1991** [Solarint/SAIN#202]
I still don't understand how to disable the return fire when bots try to hit the spot I'm shooting at. They do it with very high accuracy. Today I died from a 12/70 (MP133 or something), I didn't even hear the shot - it was maybe 300 meters or so.

I was shooting a stationary machine gun at customs for a while and got a `head/eyes` shot (ie enemy in front, not behind) as well as return fire from a SCAV (think: Tarcon, window).

Sure, I'd understand dying from a 7.62x51 or something like that from a PMC, but a 12/70 from 300 meters? What the heck.

**Comment by Solarint** [comment]
I'm adding to it every update.
