### ISSUE TITLE
SAIN errors on Ground Zero spammed in hosts log

### ISSUE THREAD

**Issue by lilasclepius** [Solarint/SAIN#205]
[Error  :      SAIN] [SAIN.Components.LocationClass] : [[Update().findLocation().parseLocation()]:] : [Sandbox_high]. Any ideas how to fix that or if it matters? I am running FIKA and these are the logs from the dedicated client.

**Comment by berkeavci** [comment]
I can confirm that I am also having this problem and somehow it affects bot spawning. It says "Donuts still waiting...".

**Comment by Solarint** [comment]
Fixed
