### ISSUE TITLE
[ Question ] Is there a setting here that supports blinding bots when using a flashlight at very close range?

### ISSUE THREAD

**Issue by gzhegow1991** [Solarint/SAIN#207]
My bots in Reserve attack me in squads, and after one attacker is killed, the second immediately takes revenge on me, ignoring my flashlight pointed at his face.

**Comment by kakahost** [comment]
It works, it's simply not so overpowered. It gives some effect during CQB, but it's pretty small. Using flashlights in mid range will protect you better, as I experienced mid-range flashlight battles.

**Comment by gzhegow1991** [comment]
thanks

**Comment by kakahost** [comment]
Close this issue, please

**Comment by gzhegow1991** [comment]
Actually config values is found inside `SAIN/BotSettings/*.json` in each personal config file. I forgot section, but it actually there.
