### ISSUE TITLE
Dedicated client errors

### ISSUE THREAD

**Issue by stk2008** [Solarint/SAIN#208]
this is showing on the dedicated client I run
https://i.imgur.com/McAR0FT.png

Log file
[LogOutput.log](https://github.com/user-attachments/files/17386712/LogOutput.log)

Thank you

EDIT

another log file closer to when the error happened.
Seems to be when leaving a RAID
[LogOutput.log](https://github.com/user-attachments/files/17387020/LogOutput.log)

**Comment by Solarint** [comment]
Should be fixed by Lacyway.
