### ISSUE TITLE
Question on SAIN with FIKA

### ISSUE THREAD

**Issue by FishGaming** [Solarint/SAIN#209]
I have a question regarding SAIN and FIKA. So if two people are playing with SAIN and since it is a bepinex mod, does it make any difference if each person has a different preset, or does having multiple people connecting into a raid with SAIN results in a difference?
 I played with a friend yesterday where I got lasered by Grenades or headshot instantly no matter the difficulty. I died 10 of our 11 raids yesterday, and we both were on less than default difficulty preset and I was the only one hosting. Today I try that and barely have to heal from not getting shot... I feel like something is up..

I know that the person hosting is supposed to have their settings only applied to raid, but the difference in the bots when playing with my friend vs today playing by myself is definitely different and not just a one raid thing. I've done 5-7 raids today and I barely am healing vs with my friend we would either die or be spending 5 minutes healing 3 limbs per fight.

**Comment by Solarint** [comment]
Only the host matters.
