### ISSUE TITLE
[ Question ] How to show circle debug of bots aiming at runtime?

### ISSUE THREAD

**Issue by gzhegow1991** [Solarint/SAIN#210]
SCAV with shotguns at 12 meters miss all shots even if I walk slowly. But with SKS they hit almost all shots in a row. What settings do I need to adjust? (I have enough experience to edit SAIN configs or personalities or global settings and I have read the explanations of the settings from online PDFs)

**Comment by Solarint** [comment]
There is no way to change specific weapon type scatter currently. Not sure how BSG sets that.
