### ISSUE TITLE
[ Possible Bug ] Reloading bots and spawning empty bags in their inventory

### ISSUE THREAD

**Issue by gzhegow1991** [Solarint/SAIN#211]
Enabled `dadGamerMode` to test bot accuracy and noticed that some bots stop shooting at me just because they have the wrong magazine loaded (empty magazine)...

Or maybe because they have empty magazines in their inventory. This happens randomly, but often, after a bot gets killed, I look through its inventory and most often I see empty magazines in the inventory, but the loaded magazine has bullets.

So I prefer the behavior where bots always have 1 empty magazine after any fight they participate in.
And always have a full magazine in the inventory that should magically appear after using the current one.
Another empty magazine should be silently removed.

This works made by BSG, but not always... Hope, we could test it and fix.

**Comment by Solarint** [comment]
What you are saying you want is how it should be working.
There are weird niche bugs that can happen but I can't decipher BSG code enough to find out why.

**Comment by gzhegow1991** [comment]
I understand. Buyanov and ITS team.
