### ISSUE TITLE
Marksman is inside Exclusion list and not available to make him stronger

### ISSUE THREAD

**Issue by gzhegow1991** [Solarint/SAIN#212]
Sabge

**Comment by Solarint** [comment]
Yup.

**Comment by gzhegow1991** [comment]
So, now SAIN contains `marksman` class to be configurable using deep configs, finally? Can i make snipers super dangerous now?

**Comment by Solarint** [comment]
No, it would require a rework of how I handle AI, they are excluded to improve performance. Sorry!
