### ISSUE TITLE
Is SAIN still being developed?

### ISSUE THREAD

**Issue by DjoleDzele** [Solarint/SAIN#213]
Just wanted to check whats the current status of SAIN, since it seems there wasn't much activity lately

**Comment by schokobon0** [comment]
solar got burnt out and is taking a break

**Comment by Solarint** [comment]
Yeah, just burnt out. I'm not sure if I will continue developing new features, but I intend to clean up and release for 3.10 once that is out.

**Comment by DjoleDzele** [comment]
Thank you for your work, not sure if i would be able to help out, used to develop in unity as a hobby, what kind of knowledge is needed for this type of project?

**Comment by Solarint** [comment]
> Thank you for your work, not sure if i would be able to help out, used to develop in unity as a hobby, what kind of knowledge is needed for this type of project?

There isn't much knowledge needed beyond how to interact with Tarkov's code if you are already familiar with Unity Scripting in C#. I can provide more info on how sain works if you would like to play around with your own branch on github.
The current code in the main branch is going to be reverted to when I last did a public release in the next few days, so I would hold off until then.

**Comment by DjoleDzele** [comment]
Sounds good, i guess i will take a look through these scripts and code these days to check how much i can understand it, last time i played around with Unity was just before getting my current full time job unrelated to programming which was almost 4 years ago haha,  but i think i wouldnt need much time to refresh my memory

I wanted to hear your opinion, what do you think are the limits of performance optimization for this code, since thats mostly what bugs me about it, especially multi core usage

**Comment by FOXS7AR** [comment]
i HOPE Solarint will give us all a last ride for 3.10 ... if not its okay too, all the best for u mate and thanks for ur SPT modding effort.

o/

**Comment by ucklefester** [comment]
hope your good, 3.10 has released and im excited to see when you update sain, its by far the best ai mod and i use no other just like many other people. take your time homie we all get burnt out some times
