### ISSUE TITLE
SPT + SAIN: shooting / aiming logic, strange head / eyes, head / jaws, head / throat, head / neck hits, helmets seem to not being hit

### ISSUE THREAD

**Issue by DivisionByZeroInfinity** [Solarint/SAIN#214]
Hi there,

thanks for the development of this AI-mod and the huge effort behind it!

While playing SPT with SAIN for now about 9 month with many hours daily, i noticed some strange behaviour of the bots while shooting, which - for me - makes playing SPT in this configuration more and more frustrating.
When i die it is about 90%+ (conservatively speaking) from either head / eyes, head / jaws, head / neck or head / throat.
My mod setup is SPT + SAIN + Questing bots + Looting bots + Waypoints + That's lit + Donuts

After dying so many times under these circumstances (head / x) i thought that this was just a problem with AI difficulty so i set Donuts to easy spawns (PMC + Scavs) and then extensively tested different settings in the SAIN configuration (F6 menu).
I tested different combinations to lower the overall difficulty, a.o.:
1.) > Global Settings > Difficulty > Vision Distance Multiplier
2.) > Global Settings > Difficulty > Vision Speed Multiplier
3.) > Global Settings > Difficulty > Scatter Multiplier
4.) > Global Settings > Difficulty > Accuracy Multiplier
5.) > Global Settings > Difficulty > Precision Speed Multiplier
6.) > Global Settings > Difficulty > Accuracy Speed Multiplier
7.) > Global Settings > Aiming > Aim Down Sights Aim Time Multiplier
8.) > Global Settings > Aiming > Global Faster CQB Reactions (off)
9.) > Global Settings > Aiming > PMCsAimForHead: off
10.) > Global Settings > Aiming > PMCAimForHeadChance: 0
11.) > Global Settings > Aiming > PartVisScatterMultiplier
12.) > Global Settings > Shoot > Global RRecoil Multiplier
13.) > Global Settings > Shoot > (Advanced) Add or Subtract Recoil
14.) > Global Settings > Shoot > (Advanced) RecoilDecayCoifficient
15.) > Global Settings > Shoot > (Advanced) DifficultyScaling

With the above settings i finally reached a point at which playing wasn't really much fun anymore due to the artificially low difficulty, BUT those deaths by head / x still happened.
While most of those deaths happened by PMC fire, there were SOME deaths caused by scav fire, but maybe that were just coincidence = bad luck = RARE lucky shots to head / x can actually still happen, even if everything is working as it should.

What bothered me further was not just getting insta-killed by head / x on a regular base (even at a now otherwise silly low difficulty), but also the fact, that helmets are totally useless, because they do NOT help against these head / x hits.
While i got killed hundred of times by this "head / x effect", not a single helmet was damaged by hits to the head - not for a single point of armor.
I tried to research on this topic and read lots of posts, mostly on reddit. While there were some players talking (writing) on similar problems, most of these complaints sadly were talked down by a majority of people commenting on these topics with posts like "your too bad", "no skill", "buy better helmet", "happens randomly / bad luck", "don't peek" etc. etc. etc.
Then i found one thread on which the OP described the exact same problem, and he elaborated on what he tried to further narrow down the problem behind these effects.
He had the same view on helmets being useless against head / x, but proposed using visors, at least against head / eyes and maybe against head / jaws (depends of the equipment, e.g. additional jaw protection).
He realized that as soon as he used a visor, even a visor with level 1 or 2 protection on a level 2 or 3 helmet, he won't get head / eyes anymore, but he started getting killed by head / neck or thorax hits - with the same instant kill effect like before, but on different body parts / hit boxes. 
I began testing different setups with visors and the AI seemed to be able to completely avoid any hit box that is protected with at least some armor. Head / neck was common, as long as i used armor vest without neck protection, but as soon as i changed to Kirasa, GB13, Korund etc., there were no more head / neck deaths.
Though hits seem to change to unprotected body parts, this - as far as i have tested - happens just from outer body parts (extremeties: arms, legs) to the torso. When you wear a helmet including visor and a body armor with neck and groin protection, then things start to feel "normal" again:
You will get mostly hits to the thorax and some hits through your visor, but again no damage to the helmet itself (which is still a strange thing).

Turning > Global Settings > Aiming > PMCsAimForHead: to on seems to not alter the problem in any way, even after i tested with > Global Settings > Aiming > PMCAimForHeadChance: to 100. AI bots didn't hit my head even when i was standing still.
Turning > Global Settings > Aiming > PMCsAimForHead: to off didn't stop the head / x effect in any way, so i don't understand what this setting is for  and/or how it is used by the aiming / shooting algorithm for the AI...(?)

Something i noticed while playing with all the different settings is that the chance for a PMC AI for killing you with head / x increases noticeably when the personality is GigaChad. After disabling this personality i got less of those head / x, but it seems not to have something to do with general shooting capabilities, as with extremely low difficulty settings on the test these GigaChads were not a threat anymore - except those head / x. Same thing applies to the "normal" Chad personality.

Sometimes when i got head / x by a PMC that AI fired their gun in a noticeably absurdly high rate of fire (with autofire guns), while normally all PMCs had a clearly slower rate of fire due to my settings to drastically increase recoil and spread (for testing purposed).
I don't think it is coincidence that this strange autofire and head / x often happen together, as both actions should be outside the rules as per SAIN settings.

As far as i can evaluate this problem, it seems to have something to do with the shooting and/or aiming logic and/or maybe some rules / settings are not applied correctly.
Right now the settings > Global Settings > Aiming > PMCsAimForHead and > Global Settings > Aiming > PMCAimForHeadChance: seem to have no effect on head / x, though normally they should.

Greetings, Oliver

**Comment by Solarint** [comment]
The aiming system is vanilla EFT with modifications, I won't be rewriting their aim system to fix these kinds of issues.

**Comment by DivisionByZeroInfinity** [comment]
I didn't know that it was just the vanilla aim system with modifications, as the name "SAIN - Full AI Replacement Mod" - at least regarding this part of the AI system - hinted me in the wrong direction.

So i guess, you didn't override their shooting logic functions but let the original function call happen and "just" inject your custom additional code before and/or after it?
During my research on this strange AI aiming / shooting behavior i realized that there are several similar complaints across reddit etc., but regarding live EFT, too. So these issues are not limited to SAIN, as you said. 
I thought these issues could be solved by SAIN because there are so many options regarding vision, aiming and shooting.
So i'll have to maybe try one of the mods with additional HP for the head as some kind of workaround.
Thanks for the clarifications.

**Comment by DivisionByZeroInfinity** [comment]
Hi,
just wanted to add that i didn't mean to offend you with that AI shooting issue.
If it looked or felt that way i am sorry! I was just a bit bothered by these constant deaths by head/eyes etc.
I'm really grateful for SAIN because it is such a massive improvement of the vanilla AI of my all time favourite game.
So thank you and happy holidays :-)
