### ISSUE TITLE
Bots stuck at door

### ISSUE THREAD

**Issue by thong123456100** [Solarint/SAIN#216]
Running latest SAIN on 3.10.2, there has been a significant increase in AI pathing issues, specifically when AI are stuck at doors, they keep running at the doors, exposing themselves but not opening or breaching the doors. I don't think this occured that often during the old SAIN on 3.9.8.

**Comment by Nizhon** [comment]
Also have noticed this, also noticeable at factory door on Customs, bots will try to run through the big red metal gate next to the factory door hut/house and don't try to find a way to get around instead. Seems doors overall don't get accounted for anymore.
Clip of door issue: https://medal.tv/games/escape-from-tarkov/clips/jgkNb1Hfd7fg-kh6W?invite=cr-MSxBOWosMzQ0MzU4NjMs
Can get more videos to show the issue.

**Comment by thong123456100** [comment]
https://www.reddit.com/r/SPTarkov/comments/1hbmolb/bots_stuck_at_doors/
My post about the same issue on Reddit has people commenting that it might be a vanilla issue rather a SAIN issue, so i'm not exactly 100% sure. However, I could confidently say that SAIN in 3.9.8 works much better than with less issues than the current one.

**Comment by Solarint** [comment]
Doors are jank because BSG's doors are jank. It wont be fixed anytime in the near future. You can enable vanilla door behavior in the F6 Menu.
