### ISSUE TITLE
Sanitar frozen

### ISSUE THREAD

**Issue by Agoelia** [Solarint/SAIN#217]
Sanitar was standing in place, I presume at his spawn point. 
His guards spawned correctly, fought and died as normal. Other bots also spawned and behaved normally. 

Other bosses in other raids did not have this issue, 

I am playing on the latest version of SPT AKI, all my mods are updated. My MOAR configs are the defaults. 

![1](https://github.com/user-attachments/assets/2913c28b-bc0b-4185-b8b9-608801b45075)
![2](https://github.com/user-attachments/assets/72f765aa-49cf-4da6-a29e-2120a7316d98)
[FullLogOutput.log](https://github.com/user-attachments/files/18140129/FullLogOutput.log)
[LogOutput.log](https://github.com/user-attachments/files/18140130/LogOutput.log)

**Comment by harmonyzt** [comment]
Saw this issue in discord SPT. It might be caused by Performance Improvements latest update.

**Comment by Solarint** [comment]
Can't Reproduce, likely another mod breaking something.
