### ISSUE TITLE
Hideout Gun Range exceptions after raid

### ISSUE THREAD

**Issue by DrakiaXYZ** [Solarint/SAIN#219]
After running a raid, going into the hideout and trying to use the gun range results in no actual gunshots, and a lot of exceptions being logged.

Steps to reproduce:
1) Run a raid
2) Load into the hideout
3) Go up to gun range and try to shoot

Logs:
[2024.12.17_0-35-04_0.15.5.1.33420 traces.log](https://github.com/user-attachments/files/18158617/2024.12.17_0-35-04_0.15.5.1.33420.traces.log)
[LogOutput.log](https://github.com/user-attachments/files/18158618/LogOutput.log)
[server-2024-12-16.log](https://github.com/user-attachments/files/18158620/server-2024-12-16.log)

**Comment by Solarint** [comment]
Fixed for 3.2.1
