### ISSUE TITLE
same error message on every version. not sure what to do 

### ISSUE THREAD

**Issue by LTMustard** [Solarint/SAIN#220]
![Screenshot 2024-12-17 143307](https://github.com/user-attachments/assets/0d7dd92c-714c-4b52-9f03-f34b37443f2f)

**Comment by LTMustard** [comment]
was an issue with one of the other mods not SAIN

**Comment by Solarint** [comment]
as the errors says. You are missing big brain.

**Comment by LTMustard** [comment]
it said issue with big brain but it was the waypoint mod wasnt a full file so i deleted waypoint and redownloaded it and it worked. ive already had big brain downloaded and it gave that error everytime so i tried the other mod and it turned out to be that one.
