### ISSUE TITLE
Bosses Have Wrong Gear

### ISSUE THREAD

**Issue by CubitalLP** [Solarint/SAIN#221]
Sincere apologies if this is a known issue, but I couldn't find it anywhere. I'm noticing that bosses consistently spawn with the wrong gear (ex. Tagilla spawning with an SR2M, defender armor, Glorious E mask, Shturman spawning with Tagilla's BOSS cap and a KS-23, etc.). Was wondering if this is a SAIN thing, an SPT thing, or some kind of bug.

Mod list:
Algorithmic Level Progression
Inory-dynamicgoons
Looting Bots
SAIN

Mod folder screenshot:
![Mods List](https://github.com/user-attachments/assets/651ee464-1f5d-43ba-9f67-868d4eec43e6)

**Comment by CubitalLP** [comment]
Adding BepiInEx log output file. I am playing on SPT 3.10.3

[LogOutput.log](https://github.com/user-attachments/files/18191729/LogOutput.log)

**Comment by Solarint** [comment]
SAIN does not alter gear for any bots what so ever. Algorithmic level progression does that
