### ISSUE TITLE
Shturman spawned without an AI

### ISSUE THREAD

**Issue by BetterBite** [Solarint/SAIN#222]
Had an occurance where Shturman failed to spawn with AI. Raid Review didn't show any difficulty next to him. His followers spawned and behaved as normal sticking with Shturman (to the North of Sawmill where he spawned) but Shturman literally spawned with no AI and did not move.

SAIN preset was default with vanilla regular Scav AI and vanilla bot chatter

No other mods that should change how AI behave or conflict with SAIN (i think)

Version is 3.2.1

Mod List
![image](https://github.com/user-attachments/assets/6e60bab8-db1a-4abd-a093-58ebbe938b0b)
![image](https://github.com/user-attachments/assets/3da10e8a-e5c8-4d53-b69b-938d50425514)

Log (2 raids, first one was with Shturman, second didn't spawn him)
[LogOutput.log](https://github.com/user-attachments/files/18204556/LogOutput.log)

SVM settings incase they might matter in some case
[hawk tuah.json](https://github.com/user-attachments/files/18204567/hawk.tuah.json)

**Comment by Solarint** [comment]
I'm not seeing anything in SAIN reporting an error. It's likely something broke before SAIN had a chance to actually set up for him. Either an error from a different mod or a vanilla EFT bug. If something fails with sain it should be very obvious in the LogOutput.

**Comment by bushtail** [comment]
We've had instances of bosses not actually shooting us with latest, I am unsure if they spawn with a personality or not, but it seems as though the issues are either related or one and the same. I can pull our logs if it'd help.

**Comment by bushtail** [comment]
UPDATE: @BetterBite remove boss notifier, it is the cause of your issues, not SAIN.

**Comment by BetterBite** [comment]
> UPDATE: @BetterBite remove boss notifier, it is the cause of your issues, not SAIN.

I'll remove it and seen if works when I get back.

**Comment by BetterBite** [comment]
seems a new version of boss notifier fixed the bug, i will presume therefore since boss notifier acknowledged it that the issue is resolved
