### ISSUE TITLE
weird teleportation bug(?)

### ISSUE THREAD

**Issue by memedoggo** [Solarint/SAIN#29]
https://i.ibb.co/6HDnymQ/Replay-2023-06-13-05-36-43.webp

Forgot the log sorry ;_;

**Comment by Solarint** [comment]
Oh thats a weird one. Its hard to tell from the gif, but that was 100% the same guy?

**Comment by Solarint** [comment]
It looks like those are actually two different bots, the first appears to have extracted. Their backpacks are different.

**Comment by memedoggo** [comment]
https://youtu.be/UJk4_FJekMs
OK, it happened again in the factory. This time I bring the log :)

``
[eftlog.txt](https://github.com/Solarint/SAIN/files/11739128/eftlog.txt)

**Comment by memedoggo** [comment]
I got bots disappearing in the factory in a similar fashion but turned out it was caused by AI Limit mod.

However the original post happened when I didn't have AI Limit installed so maybe the bot extracted like you said although I've never seen a bot doing that.
