### ISSUE TITLE
Cannot exfil at an extract that has been used by a bot

### ISSUE THREAD

**Issue by January-0002** [Solarint/SAIN#41]
I've only started experiencing this issue when using the 4.x testing build. 

I saw that one of the bots has successfully extracted on Gate 3 on factory, because all the doors were open and there was nothing there.

I tried using the exfil, but instead of my screen going dark and going to the extracted screen, my HUD just disappeared, all bot acttions stopped and all UI elements would become inaccessible, forcing me to close with an ALT+F4. 

![image](https://github.com/Solarint/SAIN/assets/39699418/498683d6-2430-49b8-af04-ba9a9f186142)

The above PNG presents the very last bits of my log, which I hope can be helpful as it seems to have caught an exception related to bots extracting.

**Comment by Solarint** [comment]
Should be fixed now in test build 4.2. Found the proper function to despawn bots without doing it in a hacky way. Let me know if you see this again, though!

**Comment by January-0002** [comment]
Yep, will do some testing and reopen the thread if it goes haywire again :) Keep up the awesome work!
