### ISSUE TITLE
Crashing at second half of raid

### ISSUE THREAD

**Issue by January-0002** [Solarint/SAIN#42]
I am unsure of what caused it but the game ran fine until maybe 50-60% of the raid was done. 

Then it ran at 10 seconds per frame (that is not misspelled, it was taking one frame 10 seconds to render).

Then it crashed.

This error log was spammed about 700 times in the log. 

![image](https://github.com/Solarint/SAIN/assets/39699418/5ed1d71d-a584-49eb-bca2-0a55bbe160dc)

Hope it's nothing too serious... 
SAIN 4.2 
Bigbrain RC2
Woods Daytime
Between the rocks, between USEC Checkpoint and ZB014 (key required exfil)

Edit: Exact location of crash below, marked with sad face. 

![image](https://github.com/Solarint/SAIN/assets/39699418/63390f36-7a87-4efd-8f46-b9a202a81017)

**Comment by Solarint** [comment]
Oh weird. Not sure why I never got that on my side, It looks like a simple error in one of my loops. I'll see if I can find it and upload a fix. Thanks for the detailed info and error log. Makes it so much easier for me!

**Comment by Solarint** [comment]
Should be fixed now. I found the problem. Test build 5 is the latest.
