### ISSUE TITLE
SAIN 5.2 - Performance Issues

### ISSUE THREAD

**Issue by January-0002** [Solarint/SAIN#44]
I have spoken to a concerned member of the discord and heard that there were potential FPS issues caused by SAIN 5.2 (latest testing). 

I decided to test it using a limit on how much AI can spawn (AI amount: medium) and the Tarky tool from SSH to simulate a worst-case scenario with a shitload of AI doing a lot of things at once, right in front of the player (teleport-to-crosshair)

I have conducted this test on the following specifications:

RX 6700XT
16GB of DDR4 3200MHZ
Ryzen 7 5800x3D

The FPS was limited to 100 for the sake of heat and freesync. This was tested on customs daytime.
The AI view distance has been set to 100m for the sake of consistency with the radar (also set at 100m)

Additional controlled variables: AI limit uninstalled to ensure consistent results; configs reset for the sake of fair testing on clean copies.

Here are the results: 

No-SAIN:

-100FPS with no AI within 100m 
-90-95FPS with a few active AI (10-12AI counted over 3 sessions)
-78-85FPS when all 20 decide to fling shit at each other in the immediate vicinity (10m)

SAIN 5.2:

-100FPS with no AI within 75m 
-75-80FPS with less than 10AI active (the worst one was with 2 AI that I accidentally encountered at the gas station post-testing, and it dropped like crazy)
-50-80FPS (very variable frame times) when all AI are engaged in shit flinging.

Since this was only a personal test, it shows nothing 100% conclusive, but given the current results and the controlled setting, it would be reasonable to conclude that there may be a cause for investigating the performance of the mod in the future.

The mod list used:

-Amands graphics
-Game hud
-DoorBreacher
-Fershite balance patch
-FragmentationDisabler
-Waypoints
-Bigbrain
-Radar
-FU inertia

No errors in log.

Sorry for the long post, here's a potato to comfort you. *gives potato*

**Comment by Solarint** [comment]
Been working on narrowing down the cause all today, this build should be vastly improved but not sure if its solved yet.
https://github.com/Solarint/SAIN/releases/tag/1.9

**Comment by January-0002** [comment]
Ok I did some preliminary testing and the results are promising.

Deleted old config, no AI limit.

SAIN FPS on Customs went as follows:

-TP all bots, immediately dropped to 80fps.
-They start fighting and dying, drops to 60
-HOWEVER, with 7 bots left, the FPS rose to about 80-85 which is a difference of 10FPS which is good.

I am unsure how much of this is BSG spaghetti code inconsistency, but the performance is most definitely getting there.

**Comment by January-0002** [comment]
Closing issue for now, as I am experiencing no further issues with performance caused by sain
