### ISSUE TITLE
Extremely Overtuned AI for CQC

### ISSUE THREAD

**Issue by January-0002** [Solarint/SAIN#46]
This is a known issue, but having 3rd party proof is important to not nerfing them too hard.

https://youtu.be/3CkqpKlLS1o

USEC reaction time was 1 second roughly, accuracy was way above what the spread would dictate (default settings). 

Related probably: Tagilla hates everyone and will shoot without hesitation, which is not vanilla behavior.

**Comment by January-0002** [comment]
Update: since update 6, the PMCs went from Absolutely Impossible to Slightly Less Impossible. They are still definitely over tuned as they 1 frame aimbot in reaction to any hit, but it's getting there.

**Comment by Solarint** [comment]
Should be fixed now.
