### ISSUE TITLE
Performance Issue With Raider Bot Generation Step

### ISSUE THREAD

**Issue by January-0002** [Solarint/SAIN#47]
Playing on labs with the last few builds (starting from 5.1) has presented a strange issue on Labs with raider generation.

As soon as a few would spawn, the normal tarkov stutter would appear, but then seconds later the FPS would sharply drop and stay at 60 (from 120). Then after 15 seconds it gets even worse and goes all the way down to 32 and stays like that for a minute or two, before it shoots back up to 120... 

This issue consistently occurs only on Labs and it occurs when raiders are generated on the map, and when their behaviors become active.

**Comment by Solarint** [comment]
Likely just coincidence and part of the broader performance issues. Should be all good now with latest builds.
