### ISSUE TITLE
SAIN Labs Performance Issue

### ISSUE THREAD

**Issue by January-0002** [Solarint/SAIN#48]
//This is a reopen of the recently closed performance issue, which was believed to be fixed.

As the newer versions of SAIN have come out, I've gone ahead and tested the latest testing version (7.3) against every previous build to find the issue start.

The issue started between 5 and 5.21 (I did not have the builds in between) as this issue does not occur on any SAIN version below 5 (tested on 4.3)

Unfortunately, as well, the issue has not gotten better... It has turned significantly worse. 

The first 3 minutes of a raid now run below 30 FPS with the latest builds of the testing version of SAIN. 
Console outputs absolutely no errors.
FPS shoots back up after those 3 minutes, but if you get spawned close to raider or PMC spawns and they spot you, you can only pray to your deity, because you're not gonna be able to fight them at a cinematic 22 FPS. 

One additional observation is that with the bugged version of SAIN, my PC fans do not spin up hard on the newer build during bot generation... Resource usage issue could be possible.

I'm happy to help test any potential fixed versions as well, however for now, this issue is here.

It also does not sound like a coincidence either... something happened between 4.3 and 5.21 which caused this.

This happens only on Labs. The issue has also been tested on a clean copy of SPTarkov, and I have made sure that bigbrain and waypoints are not causing the issue.

**Comment by Solarint** [comment]
Are you still experiencing it on the beta 2 release build?

**Comment by Solarint** [comment]
I think the problem is *actually* resolved now. Let me know if it still happens on Beta 2 Hotfix. It was likely because bots could never find an exfil there because all of them require an action before being enabled.

**Comment by January-0002** [comment]
F I X E D!
