### ISSUE TITLE
AI run out of ammo

### ISSUE THREAD

**Issue by Vaiine** [Solarint/SAIN#49]
Hi. I love the mod; it's a great addition to base SPT.

My problem is that the AI is running out of ammo when fighting.

I know this could be avoided by improving the AI, but I've got them to a healthy medium where I don't get lasered at any distance past 80m.

If there's an option to toggle infinite reloads for bots, I'm sorry to waste your time.

I'm running SPT 3.5.7, and my mod list is as follows:

Drakia Waypoints 1.0.4
More Checkmarks 1.5.1
Drakia Bigbrain 0.1.2
Sain 2.0 beta 1
Skwizzy Looting Bots 1.0.2
Glided Key Storage 1.1.0
Nookys SWAG preset 1.2.4
Swag 1.4.4
POOP1.5.2

If you want additional information, I'm happy to help!

Thanks again!

**Comment by Solarint** [comment]
Update to newest looting bots version and update to SAIN beta 2. It was released yesterday. Make sure to get newest bigbrain update as well.
Are bots running out of ammo with the weapon they start with? or is it something they looted?

**Comment by Vaiine** [comment]
I'll get them updated.

Yes, it's the weapons they spawn with.

I'm not too tech-savvy, but it could be that sometimes they only bring one or two magazines spare, and if they are killing a few scavs/PMCs they are bound to run out of ammo.

**Comment by AlexeySkinny** [comment]
А разве это не фишка? Пусть кончаются патроны. Если кончились, пусть подбирают с убитых оружие и патроны. Реалистично и гениально просто!)

**Comment by Vaiine** [comment]
Alexey, yes it does add to the realism, but I feel it ruins the vibe of the game when I find a PMC who is standing out in the open shouting "mag change" and "need to reload", not fighting back.

**Comment by AlexeySkinny** [comment]
Тут нужно чтоб ЧВК искал патроны у убитых, подбирал оружие и использовал его в случае если на основном оружии в магазинах пусто. В таком случае логика есть. Если уж и добавлять такую функцию то в полном объёме. А так да, патронов нет, стоит и кричит...ну бредово. Да, по поводу того что стоят и кричат/разговаривают, заметил это и на заводе и на таможне. Просто стоят и тупят. Раньше не было, а вот в последних версиях вылезло. На заводе так стоят по углам и разговаривают, комментируя происходящее. Кто то бывает передвигается, но всё поломано.

**Comment by Flame1211** [comment]
just wanted to comment that im also currently having bots run out of ammo, I have SAIN 2.0 3.4.3, Lootingbots 1.1.1_3 and bigbrain 1.4

**Comment by Solarint** [comment]
Issue was caused by Gilded Key Storage, ( I was using it too and pulling my hair out at what was causing it )

**Comment by Flame1211** [comment]
just wanted to bump this back into the open, I seem to be getting this issue again, even with version 1.1.2 of gilded key.

**Comment by Solarint** [comment]
Its gilded key or something else causing it most likely. I developed SAIN without it and never saw the issue, nothing I can do about it if another mod is causing it. Sorry
