### ISSUE TITLE
Прострелы и обнаружение

### ISSUE THREAD

**Issue by AlexeySkinny** [Solarint/SAIN#51]
Заметил баг, что если ты находишься даже вне поле зрения, боты кричат о том, что видят тебя. Реплики соответствуют как при прямой видимости. Даже если ты за укрытием, или в здании и тебя вообще не видно. В моём случае это было со свитой Решалы в общежитии. В следующем рейде заметил ещё баг, всё у той же общаги. Когда перебегал от костра к 3 этажному зданию по мне открыл огонь дикий, сквозь кусты и прочее, с репликами прямой видимости. Я был за горкой, и он так же отчётливо кричал что видит меня, как и в первом случае. Стоило только высунуть голову чуть выше горки, сразу прилетело голова/глаза через кусты. Я пытался его вообще увидеть, но так и не обнаружил. Свита кстати так же настреливает очень хорошо, даже если ты в тёмном здании, за стеклом. Как только твоя часть тела покажется на линии огня, они сразу среагируют и начнут стрелять.  Либо у них рентгеновское зрение, либо я не знаю)

**Comment by Solarint** [comment]
Должно быть исправлено в последних версиях. Это был баг с проверками зрения.
Кроме того, не могли бы вы перевести свои комментарии с помощью переводчика Google или какой-либо альтернативы? Мне приходится копировать и вставлять каждый раздел самостоятельно, и мне требуется некоторое время, чтобы понять, в чем проблема. Спасибо!

**Comment by AlexeySkinny** [comment]
Certainly! I will translate through Google. I don't want to take time.

**Comment by LittleOneChewy** [comment]
Same problem here on customs (maybe other areas too, dont know for now) with beta 3.2. Bots see me through any type of windows 100+ meters away and shoot.
Died while was on 2nd floor in library near wall, shoot was from Reshala base. Dorms 2nd floor, shoot through curtains and glass from road near factory shacks.
I dont have any other AI mods and follow all faq guide about SPT (pmc type change disabled).
Thanks!
