### ISSUE TITLE
When running on 3.5.8, i get a infinite loading screen.

### ISSUE THREAD

**Issue by TheSh1ver** [Solarint/SAIN#52]
I have no other mods than yours and its dependencies. this happened while loading into the game for the first time. It runs with out any mods.

**Comment by Solarint** [comment]
please upload your Bepinex/Logoutput file somewhere so I can see if there are any errors

**Comment by TheSh1ver** [comment]
[LogOutput.log](https://github.com/Solarint/SAIN/files/11870718/LogOutput.log)
the server seems to keep repeating these two lines, [Client Request] /launcher/profile/info
[Client Request] /launcher/server/version, it doesn't repeat them quickly maybe ever 30 seconds ish

**Comment by TheSh1ver** [comment]
last comment included the log output file.

**Comment by TheSh1ver** [comment]
the new versions seemed to have fixed the problem, thank you for the quick fix and for the incredible mod. SPT will always be better with your mod in it. Thank you again for everything you do.

**Comment by Solarint** [comment]
Not sure what I fixed, but great! I was never able to find out why this was happening for you.
