### ISSUE TITLE
Boss AI seems to not be affected by noESP

### ISSUE THREAD

**Issue by ElSkipperino** [Solarint/SAIN#56]
Hi, First of all thanks for your hard work its really appreciated <3
One thing i noticed or would like to ask, is that bush esp still seems wonky. Maybe its skill issue on my side, then just tell me :) but i just wanted to share this:

Bots love to sit in bushes 99% covered or lie down in tall grass like Pokemon and then just shoot you like nothing is there (I naded him though, and lied down in his position and no chance a human could see through the grass). Is it possible that bush esp only kinda works if i, the player is covered by bushes and not the bot? And sometimes it looks like they can shoot you through the tiniest of "holes" in a tree without even using a scope.

It seems like boss AI is strait up ignoring any kind of cover.
Is there anything i can do LOG wise or maybe settings wise that might help?

I am on the newest release of SAIN, SPT, Big Brain mod and looting bots. I did not install any other AI mods (no realism mod or anything)

Modlist:
```

G:\SPTARKOV358\User\Mods> Get-ChildItem -Name

aaMFACSHOP

aBoopsQuestZoneAPI_v1.0.0.0

ACOG4Life-OpticRework

AKGUYShop

Anastasia

Armalite-Reloaded

AUG_AttachmentPack

bluehead-AIOTrader

FershteBalancePatch

Kiki-DegredationRemover

M Guns

MFAC GEAR

MoreCheckmarksBackend

ODT-ItemInfo-3.2.0

PreyToLive-BetterSpawnsPlus

Priscilu

RainbowPC-LotsOfLoot-2.0.7

SamSWAT-L85A2

ServerValueModifier

Skwizzy-NoDiscardLimit-1.0.0

Svetlana

TingleSlayerParkov-LessOverdamage-1.0.1

Virtual's Custom Quest Loader

zSolarint-SAIN-ServerMod

zzDrakiaXYZ-Waypoints

Load Order Editor.exe

order.json


G:\SPTARKOV358\BepInEx\plugins> Get-ChildItem -Name

DrakiaXYZ-Waypoints

kmyuhkyuk-EFTApi

kmyuhkyuk-GamePanelHUD

MoreCheckmarks

SamSWAT.HeliCrash

ssh

aki-core.dll

aki-custom.dll

aki-debugging.dll

aki-singleplayer.dll

AmandsGraphics.dll

ConfigurationManager.dll

DrakiaXYZ-BigBrain.dll

DrakiaXYZ-SearchOpenContainers.dll

dvize.FUInertia.dll

FOVFix.dll

Kobrakon-TakeABreak.dll

LICENSE

notGreg.UniformAim.dll

RecoilStandalone.dll

SAIN-3.5.8.dll

skwizzy.LootingBots.dll

Uniform-Realism_Bridge.dll

VisceralDismemberment.dll

VisceralRagdolls.dll

VolumetricBloodFX.dll


```

**Comment by January-0002** [comment]
That is a known issue, even with the base DLL for NoBushESP.

Additionally, you are trying to left peek. You think you're in cover but a lot of your body is actually visible. Peek right if you want to abuse AI.

**Comment by ElSkipperino** [comment]
Haha allright, thanks for the info. So it isn't completely my fault i get destroyed from time to time by the bosses :D Thanks for the hint with peaking right, makes sense. I would consider this closed then and ill just be happy if it gets fixed in a future update.
