### ISSUE TITLE
The Bushes Give Callouts

### ISSUE THREAD

**Issue by S1rCumcision** [Solarint/SAIN#57]
Hey Solarint,

Yeah basically I'll be on the opposite side of a bush of an enemy and the bush will give callouts to the enemy telling them exactly where to shoot.

Jokes aside, in the current version 2.0 Beta 3.3 for 3.5.8, AI behaves as if there are no trees, bushes, or other foliage present and seem to see right through them. Even with no Bush ESP enabled, I've been killed over and over again through foliage not even during a firefight. The AI seems to be able to see and start shooting at you through foliage without prior knowledge of your position. I love the mod, but I've had to disable it when playing maps with lots of greenery such as Customs. I've seen others complain about the same issue in the comment section of your AKI Workshop, so I figured I'd add my own experience just to help bring it to your attention. I do also notice AI walking backwards towards gunfire they may be investigating. Very much looking forward to playing a version that has this issue fixed. I'm running 
 SPT Realism Mod, Looting bots, Big Brain, and Waypoints along side your AI overhaul.

Best regards

**Comment by harmonyzt** [comment]
1) Please update SAIN to the latest version (2.0 BETA 3.4.3)
2) Yes, they do walk backwards the gunfire or look in wrong directions, or wallhack an enemy when they hear a gunfire, this is a known issue as mentioned by the developer earlier
3) As SPT Realism Mod page says - Make sure to disable PMC Types in the Realism config app. I recommend reducing bot difficulty in SAIN's config to compensate for the lower recoil of Realism's weapon balance. Just reassure you have do that!

Sometimes when you stand on one place for too long they will eventually come to you or spot you and start shooting, when loosing vision on you they will just start spraying in the direction they saw you for the last time. This might be the case too! This mod is really unpredictable much, even I can't tell now really but I hope I helped you with at least some of the information :)
