### ISSUE TITLE
Spinning and pacing AI

### ISSUE THREAD

**Issue by Coal676** [Solarint/SAIN#63]
Hey

didn’t see this in here, but saw it in the comments on spt aki.

I am experiencing a ton of bots(mostly pmc) doing some wicked rotation and constantly shooting and pacing back and forth- sometimes they lock on to me, but I can get pretty close without them agroing- it kind of varies depending on what environment they are in. I think it is mostly with “chad”- “giga chad” classes. I have noticed it across all maps I’ve played.

I don’t know if it’s connected at all or is just because of BSGs audio changes but they also seem to be shooting behind some sort of invisible barrier because the sound of their shots go in and out when this happens too.

I am currently doing the mod combo of:

swag+donuts
Waypoints
Looting bots
Big brain
Sain
Visceral dismemberment(have tried it off and on)
Universal weapon mods
Fontaines Fov fix, Geoff’s scope update, combat stances
Svm: Just insurance and loot changes
Amanda’s Graphics

I have also edited time limits for each map in spt data extending the raids to 1:30:00

Appreciate y’all looking at this and keep up the great work!

**Comment by Solarint** [comment]
It's an issue that's being looked into, hopefully next release version will have it fixed. Been a hard one to track down.

**Comment by Coal676** [comment]
Sweet thanks- I’m going to try everything the same with swag 2 in stead of with donuts to see if that does anything because right now it’s sort of game breaking and had no issue prior to that update

**Comment by Coal676** [comment]
Just an update:

haven’t had any issues with everything same(most recent Sain) and swag 2 in place-not one bot spinning around.

**Comment by harmonyzt** [comment]
Happens to me as well! Most of the times in night raids some of them (across the map) will start spinning/shooting in random directions until their mags are empty or direction they killed an enemy which is already dead. Sometimes throws this in the console:
```
EXCEPTION: System.NullReferenceException
  at (wrapper managed-to-native) UnityEngine.Component.get_transform(UnityEngine.Component)
  at EFT.EnvironmentEffect.IndoorTrigger.Check (UnityEngine.Vector3 pos) [0x00010] in <89c8c8aab2ad44ff89f90df9bc38d688>:0 
  at EFT.EnvironmentEffect.TriggerGroup.Check (UnityEngine.Vector3 pos) [0x00052] in <89c8c8aab2ad44ff89f90df9bc38d688>:0 
  at EnvironmentManagerBase.method_1 (UnityEngine.Vector3 pos) [0x0000a] in <89c8c8aab2ad44ff89f90df9bc38d688>:0 
  at EnvironmentManagerBase+Struct52.MoveNext () [0x00143] in <89c8c8aab2ad44ff89f90df9bc38d688>:0 
```
Despite me using nothing but SAIN and Waypoints. Pretty annoying and really hard to catch but when it happens, half of the raid goes nuts.

**Comment by Solarint** [comment]
Issue should be fixed now in latest versions
