### ISSUE TITLE
Home key not bringing up sub-menu for difficulty settings.

### ISSUE THREAD

**Issue by BIG-LOAD** [Solarint/SAIN#66]
Using Sain Beta 3.0 for 3.5.7 and getting beamed with no chance of survival from pmcs and have heard of the menu to change accuracy however the home key does not bring up the menu. Currently using MoreCheckmarks,BSP,Waypoints,looting bots, take a break, No grenade esp.

Is there a way to change the key for the menu in configs or is another mod utilize the same key?

**Comment by AlexeySkinny** [comment]
As far as I know, the "Home" key appeared only in the latest versions and works on the latest version of SPT, namely 3.5.8. On version 3.5.7 this does not work, as well as in principle the latest version of SAIN. You need the latest working version for 3.5.7, or you need to upgrade your SPT to 3.5.8.
