### ISSUE TITLE
Bots spotting and firing at me from 300+ meters 

### ISSUE THREAD

**Issue by MysteriousStains** [Solarint/SAIN#70]
I had an issue in my last raid on woods that made me realise this issue has been happening long before I realised it was there. I was walking near the lake on woods and a bot on the other side of the lake started firing at me. This was about ~350m away.

I have been wondering why after installing this mod I have had no idea where I am being shot from. I am curious if this ties in with a separate issue were the user claims the bots could have a sort of x-ray vision.

Or maybe I just have my config set up wrong? 

Either way, I hope I can be helped and perhaps I can help.

**Comment by Solarint** [comment]
300 meters is far outside any bot vision distance, so unless something weird is going on with something in the default bot code, nothing I can do to change that.
