### ISSUE TITLE
Zryachiy Hostile Regardless of Encoded Transponder Status

### ISSUE THREAD

**Issue by KryptonNight** [Solarint/SAIN#71]
**Mod List for SPT AKI 3.5.8**
1. Server Value Modifier 1.6.5 (Only using this to increase loot multiplier to 3. Nothing else is modified or enabled)
2. SWAG 3.0.5
3. SAIN 2.0 Beta 3.4.4
4. Waypoints Expanded Bot Patrols and Navmesh 1.1.2
5. Looting Bots 1.1.2
6. Big Brain 0.1.4
7. Visceral Dismemberment 1.1

**Load Order for SPT AKI 3.5.8**
1. Server Value Modifier 1.6.5 (Only using this to increase loot multiplier to 3. Nothing else is modified or enabled)
2. SWAG 3.0.5
3. SAIN 2.0 Beta 3.4.4
4. Waypoints Expanded Bot Patrols and Navmesh 1.1.2
5. Looting Bots 1.1.2

**Issue Description**
Zryachiy will shoot me on sight when approaching the bridge to cross to lighthouse. I've been shot by Zryachiy as far as the shack on the beach close to the dirt road leading to the bridge. I have an encoded transponder and am able to cross the bridge without the claymores blowing up, but Zryachiy will continue to try to neutralize me regardless of the transponder's status. Zryachiy's two guards do not shot at me, though I have seen some instances where one of them will try to cross the bridge and blow up. It's usually the guard on the right hand side when crossing the bridge that this happens to. 

If I make it across the bridge and get through the doors to the courtyard, Zryachiy will continue to try to eliminate me. He also tends to move from his position and follow me around lighthouse as well. This has been an issue for a solid while now for me. I've been able to stop Zryachiy from opening fire on me when I remove SAIN from the mods folder. I just don't know if SAIN contains a bug or if something else is wigging his AI out as a potential conflict. Below is the Bepinex log along with a video displaying Zryachiy's odd behaviors. I hope I supplied enough info to help out here.  

**Bepinex Log**
[LogOutput.log](https://github.com/Solarint/SAIN/files/12170453/LogOutput.log)

**Zryachiy Being a Mean Bully**
https://youtu.be/ssAbvKezxVQ

**Comment by Solarint** [comment]
I am aware of the issue, future major versions will have it fixed.

**Comment by Solarint** [comment]
Should be fixed now
