### ISSUE TITLE
[SPT 3.6.x] Bots randomly dissapear after being killed

### ISSUE THREAD

**Issue by harmonyzt** [Solarint/SAIN#74]
Throughout dozens of raids I noticed that taking out PMCs and others became somewhat easier. With that in mind I have seen a lot of PMCs or followers, bosses, SCAVs let it be anyone would just start pulling meds out and start healing/and running away or just looking at you while healing when you are in their direct sight line(from 1m to ~100m), no matter the distance they'd sometimes consider healing when actually they should fight to death! I can't provide screenshots or media as for now but I will update this issue with some media once I find that occurrence again! Just letting you know that their desires are somewhat broken, other than that everything is perfect. Thanks in advance :) 

Mods that have been used in all the raids:
BotCallsigns
MoreCheckmarks
Platinum-EyesOfATrader
SBNV
Skwizzy-NoDiscardLimit
SWAG + Donuts
SAIN
zzDrakiaXYZ-Waypoints
AmandsGraphics
DrakiaXYZ-BigBrain
DrakiaXYZ-TaskListFixes
skwizzy.LootingBots

This was seen on the latest versions

**Comment by harmonyzt** [comment]
Mostly fixed in SAIN.2.0.Beta.3.5.Test.10.for.3.6.0. However I've noticed some bots disappear after being killed with just their gun floating above the ground. 

Pretty sure this is related to this error, I suggest taking a look and tell me if this is related to SAIN in any way - `EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.`
Here are the logs, this error is pretty common (maybe I am just a little dumb and using SAIN on 3.6.1, but still):
[2023.08.09_15-46-26_0.13.1.3.25206 errors.log](https://github.com/Solarint/SAIN/files/12305712/2023.08.09_15-46-26_0.13.1.3.25206.errors.log)

[LogOutput.log](https://github.com/Solarint/SAIN/files/12305730/LogOutput.log)

**Comment by Solarint** [comment]
Drakia was able to reproduce this with a clean SPT install, so it seems its a gift from BSG. Nothing I can do about it.
