### ISSUE TITLE
Slighty undertuned bots at night times 

### ISSUE THREAD

**Issue by harmonyzt** [Solarint/SAIN#77]
This happens occasionally but when it happens, it happens and even when I'm clearly visible (under some light source, for example) they won't shoot you unless you just stand still for a couple of seconds and wait until they will go a bit closer.

Here's the clear example:
https://www.youtube.com/watch?v=MqQK5d7ivSM

Logs in case
[LogOutput.log](https://github.com/Solarint/SAIN/files/12310943/LogOutput.log)
[2023.08.10_7-45-29_0.13.1.3.25206 errors.log](https://github.com/Solarint/SAIN/files/12310946/2023.08.10_7-45-29_0.13.1.3.25206.errors.log)

**Comment by Solarint** [comment]
Unfortunately there's really nothing in the default code to track if a player is in a light source or not, I would have to code it all myself from the ground up, which wont be happening any time soon.
