### ISSUE TITLE
Sain broke my shit

### ISSUE THREAD

**Issue by MaximusArtilles** [Solarint/SAIN#79]
Hey mate, just added SAIN after a fresh install and something out of BigBrain, Waypoints and Sain has made the game unplayable. I keep getting the "failed to recieve backend data" error message whenever I do certain things like fold a stock. I can't start a game and I don't know how to remove SAIN without fucking the rest of the install. I've tried a couple versions and they're all the same.

I'm currently running;
SPT AKI 3.6.0
KMC SVM 1.6.5
BigBrain 0.2.0
Waypoints 1.2.0
BackDoorBandit 1.5.0
kmyuhkyuk-EFTApi
kmyuhkyuk-GamePanelHUD

I'm on version 3.4.5 now, just working through the list trying to find a version that works. it's looking like a backup and fresh install right now because I can't even extract the SAIN files I just dropped in because they auto-feed.

![SKP AKI fucked](https://github.com/Solarint/SAIN/assets/142274881/04770375-86fa-4b35-a18d-6fbc65b9475e)

**Comment by Solarint** [comment]
Nothing in sain affects items or stock folding. It's something else. After you see this error, upload the contents of the file "Bepinex/LogOutput.log" to Pastebin.com and I'll see if I can find any issues from it.

**Comment by DrakiaXYZ** [comment]
Nothing in SAIN/Waypoints/BigBrain would be causing the error you're seeing
You're running an old version of SVM.

As for uninstalling, you literally just delete the SAIN DLL from `BepInEx/Plugins`, and the SAIN folder from `user/mods`, I don't know why you would think a reinstall would be necessary.

**Comment by itsTINYTEETH** [comment]
What do you mean "fucking the install"? Uninstalling any of the mods you listed will have NO negative effects on your profile (provided you install/uninstall all dependants)

**Comment by MaximusArtilles** [comment]
I'm updating to the newest version of all the mods listed, I'll put Sain/WayPoints/BigBrain. Apologies for the vagueness, I'm a layman. I didn't realise all I had to do was delete two things and it wouldn't leave a wound in my install. If I find errors I'll keep y'all updated.

**Comment by MaximusArtilles** [comment]
Fresh Installed on all newest versions, same mods. Seems to be going fine. Sorry for the troubles
