### ISSUE TITLE
Disappearing death body.

### ISSUE THREAD

**Issue by FiveFme** [Solarint/SAIN#80]
It happened 3 times out of about 80 raids (2x Woods, 1xCutsoms). Cannot pick up this weapon.

ModLoader: loading 5 server mods...
Mod: **FleaMarketPriceUpdater** version: **3.1.2** by: **Lua** loaded
Mod: **MoreCheckmarksBackend** version: **1.5.7** by: **VIP** loaded
Mod: **NoDiscardLimit** version: **1.1.2** by: **Skwizzy** loaded
Mod: **SAIN** version: **3.5.0** by: **z-Solarint** loaded
Mod: **DrakiaXYZ-Waypoints** version: **1.2.0** by: **DrakiaXYZ** loaded

[LogOutput.log](https://github.com/Solarint/SAIN/files/12363639/LogOutput.log)
![20230816211440_1](https://github.com/Solarint/SAIN/assets/142452283/4592a898-6e7e-4772-ae3f-460f56de721f)

**Comment by Solarint** [comment]
Thanks for providing your logoutput. Only error I'm seeing is from "[Error  :CactusPie.MapLocation]"
Not sure if this is the cause or not though. Without any errors from SAIN, its impossible to know if its that, a default EFT bug or something else entirely.
