### ISSUE TITLE
Plugin Fails 

### ISSUE THREAD

**Issue by Cxlvar** [Solarint/SAIN#83]
Mods: 

Amands Graphics 
SAIN 2.0

When I load up SPTarkov it displays:

' 1 Plugin failed to load due to errors. Please check the console for details ' 

I know it isn't the Amands Graphics as this DOES work but for some reason the SAIN 2.0 isn't working

Any fixes?? Would be much appreciated :)

**Comment by Solarint** [comment]
Do you have SAIN's dependencies? It will not work without it.
