### ISSUE TITLE
Performance Issue/Crashing?

### ISSUE THREAD

**Issue by rube-romp** [Solarint/SAIN#84]
I'm encountering an issue that seems like a memory leak, but not typical SPT memory leak issues. I've had no issues since my last clean install about a few days ago, and only began encountering the issue today (fiveish hours of in-game time). The issue includes choppy gameplay (about 10 seconds of normal gameplay, followed by ~2 freeze), and occasionally crashing (BSOD). I've checked my logs and the error log seems to be _way_ bigger than I recall (58,000 KB).

Within this error log there are three entries (repeated thousands of times over a very small window).

**The first:**
`2023-08-27 08:33:11.606 -04:00|0.13.1.3.25206|Error|Default|Node 64899f4189de40533661a0c0 have no parent`

This error references many different nodes. Some connect to vanilla items in the game, others appear to not be actual item IDs I can look up. I don't think this error pertains to SAIN.

**The second:**
`2023-08-27 08:54:29.209 -04:00|0.13.1.3.25206|Error|Default|can't find mags to reload`

Not much to say about this one, but I think it connects to the third error.

**The third:**
![2](https://github.com/Solarint/SAIN/assets/138739485/431fca86-a71e-4efa-abb9-5352f83a3cc4)
Followed by...

![3](https://github.com/Solarint/SAIN/assets/138739485/1fbc8ae3-6575-4eb1-9cef-e3a828fdea4a)
Followed by...

![1](https://github.com/Solarint/SAIN/assets/138739485/9993f20a-83be-4397-a91d-345ff51fcd59)

This specifically references SAIN, and seems to involve a reloading-related behavior, and this particular snippet is the one reiterated thousands of times.

Even if this isn't the source of the performance issues, can you tell me a little about this error and how I might resolve it?

I can't upload the error log because it exceeds GitHub's limits, but it contains pretty much just what youve seen here.

Mods List:
![4](https://github.com/Solarint/SAIN/assets/138739485/433632d5-787f-408c-a94b-f7ee05a04905)
BepInEx:
![5](https://github.com/Solarint/SAIN/assets/138739485/e5bbc9cc-b955-4881-baf2-e1c829d5cf43)

Thank you for your time!

**Comment by Solarint** [comment]
Not sure about this. It looks like an error in the EFT code which results in errors in SAIN later.  Does it happen consistently?

**Comment by omegarekrut** [comment]
> Not sure about this. It looks like an error in the EFT code which results in errors in SAIN later. Does it happen consistently?

Yes. Actually I've got the same situation here, and reinstalling the game won't help me whatsoever

**Comment by Solarint** [comment]
Hopefully it'll be fixed in the next tarkov build. Not sure if there is anything I can do without patching and rewriting Tarkov's own code here. Sorry I don't have a actual fix currently.
