### ISSUE TITLE
Soft lockup during looting process? Blurred screen.

### ISSUE THREAD

**Issue by DrYmath** [Solarint/SAIN#86]
Server version
3.6.1
Game client version
0.13.1.252606 

Seems SAIN is either an issue for me or is not playing nice with other mods of mine.

Here is my forum post with the issue: [https://hub.sp-tarkov.com/forum/thread/3638-modded-client-soft-freeze-when-searching-lootable/](url)

> List of used mods
KMC SERVER VALUE MODIFIER (SVM)
ALGORITHMIC QUEST RANDOMIZER
IMMERSIVE RAIDS
ALGORITHMIC LEVEL PROGRESSION
NO BUSH ESP
AMANDS'S GRAPHICS
LOOTING BOTS
VISCERAL DISMEMBERMENT
WAYPOINTS - EXPANDED BOT PATROLS AND NAVMESH
BIGBRAIN
SWAG + DONUTS - DYNAMIC SPAWN WAVES AND CUSTOM SPAWN POINTS
SAIN 2.0 - SOLARINT'S AI MODIFICATIONS - FULL AI COMBAT SYSTEM REPLACEMENT
GUNSMITH
AMMO STATS IN DESCRIPTION
New character profile level 1, load into factory. The bug is present on other maps, not just factory.
Usually happens a few minutes into raid once I start looting, could be a jacket, box, vest or backpack, basically anything that's searchable.
Once I initiate the search, the little wheel that tells you the search is happening freezes, Upon further testing the bug can trigger at any point during the looting process, and the loot window can no longer be interacted with.
I should clarify that this is an intermittent issue, I can loot scavs, pmcs, boxes with no problem until it hits, so I'm assuming there's an item or items that the client doesn't like and it only freezes when those items are present)
You can close the loot window but now your view is completely blurred (as it is when your in the character screen) you can't move or interact with your environment other than looking around with your mouse.
No menu will appear in the ESC menu, blindly moving the mouse around you will not "hear" the menu buttons.
Server console doesn't have any obvious errors that I see.

Client log file
[codepaste.sp-tarkov.com/?e6c3e…YcVxtTLhn8bsYPv1Ue6W9PkVK](https://codepaste.sp-tarkov.com/?e6c3e53673387dd3#CgTqxbZhH6CQFMdAQ9pYcVxtTLhn8bsYPv1Ue6W9PkVK)

BepInEx log file
[codepaste.sp-tarkov.com/?f8d17…mXyAiZ3zm2Tk2mW2jMRTfQQGQ](https://codepaste.sp-tarkov.com/?f8d17133e70edc65#87fmGg42aWKfUGgiGEJmXyAiZ3zm2Tk2mW2jMRTfQQGQ)

Server log file
[codepaste.sp-tarkov.com/?478fa…yf7kHPJNDfnAgzEvEz3w8autY](https://codepaste.sp-tarkov.com/?478fab3921d6b7f9#Htzq4zMg3oGRTvk2g4Hyf7kHPJNDfnAgzEvEz3w8autY)

I've been trying to narrow down what's causing the bug, when I removed SAIN I was able to make it through 3 raids without seeing the issue (previously I haven't been able to make it even through one raid, with some raids only lasting a few minutes before the issue arises). I added SAIN back into my mod list and the issue happened almost right away.
![Untitled22](https://github.com/Solarint/SAIN/assets/143661290/6dcd49b2-9f57-4016-980d-115d625336eb)

**Comment by Solarint** [comment]
No errors from sain, and sain doesn't touch anything to do with looting. Not sure what the issue is but I'm 99% sure its not sain.
