### ISSUE TITLE
Bots prefiring and shooting with accuracy through foliage

### ISSUE THREAD

**Issue by GetTalented** [Solarint/SAIN#87]
Mods and plugins lists: 
![Screenshot (107)](https://github.com/Solarint/SAIN/assets/143885204/8591870b-8d22-47b1-8e30-ee56f5a062ea)
https://imgur.com/kbZx5wF (if you need it)

LogOutput file:
[LogOutput.log](https://github.com/Solarint/SAIN/files/12504057/LogOutput.log)

Description:
Bots are shooting accurately through foliage. PMCs and scavs are both doing it. I also seem to be having a regular issue with extremely accurate bots, scavs and pmcs. I am playing with VAl, so I don't know if that is causing the issues or what, but I am consistently being headshot like 8 times in a burst.

**Comment by Solarint** [comment]
Does this happen with only SAIN + its dependencies? I've never seen this in my own testing and development, so it may be something else interacting with it.
