### ISSUE TITLE
Punisher mod incompatibility

### ISSUE THREAD

**Issue by toxicspike** [Solarint/SAIN#88]
Hi Sain,
I'm experiencing following issue:
Whenever the punisher from the rogue justice mod appears, I'm getting spammed with this message in the console:

![image](https://github.com/Solarint/SAIN/assets/10299219/a3e59d5c-bd61-4ca4-b155-736e364cc3b0)

With occasionally also this error displaying:

[Exception] : NullReferenceException: Object reference not set to an instance of an object
SAIN.SAINComponent.Classes.SAINHearingSensorClass.CheckSoundHeardAfterModifiers (IAIDetails player, UnityEngine.Vector3 position, System.Single power, AISoundType type, System.Single& distance) (at <2d9e4aaae7c2462da4a360dafd138280>:0)
SAIN.SAINComponent.Classes.SAINHearingSensorClass.EnemySoundHeard (IAIDetails player, UnityEngine.Vector3 position, System.Single power, AISoundType type) (at <2d9e4aaae7c2462da4a360dafd138280>:0)
SAIN.SAINComponent.Classes.SAINHearingSensorClass.HearSound (IAIDetails player, UnityEngine.Vector3 position, System.Single power, AISoundType type) (at <2d9e4aaae7c2462da4a360dafd138280>:0)
GClass635.PlaySound (IAIDetails person, UnityEngine.Vector3 position, System.Single power, AISoundType type) (at <8a5b326544954fa79c970c303424f3af>:0)
SAIN.Helpers.HelpersGClass.PlaySound (IAIDetails player, UnityEngine.Vector3 pos, System.Single range, AISoundType soundtype) (at <2d9e4aaae7c2462da4a360dafd138280>:0)
SAIN.Helpers.AudioHelpers.TryPlayShootSound (EFT.Player player, AISoundType soundType) (at <2d9e4aaae7c2462da4a360dafd138280>:0)
SAIN.Patches.Hearing.TryPlayShootSoundPatch.PatchPrefix (AiDataClass __instance, EFT.Player getPlayer, AISoundType soundType, System.Single& ___float_0) (at <2d9e4aaae7c2462da4a360dafd138280>:0)
(wrapper dynamic-method) AiDataClass.DMD<AiDataClass::TryPlayShootSound>(AiDataClass,EFT.Player,UnityEngine.Vector3,AISoundType)
EFT.Player.OnMakingShot (EFT.InventoryLogic.IWeapon weapon, UnityEngine.Vector3 force) (at <8a5b326544954fa79c970c303424f3af>:0)
(wrapper dynamic-method) EFT.Player+FirearmController.DMD<EFT.Player+FirearmController::InitiateShot>(EFT.Player/FirearmController,EFT.InventoryLogic.IWeapon,BulletClass,UnityEngine.Vector3,UnityEngine.Vector3,UnityEngine.Vector3,int,single)
EFT.Player+FirearmController.method_52 (EFT.InventoryLogic.Weapon weapon, BulletClass ammo, System.Int32 chamberIndex, System.Boolean multiShot) (at <8a5b326544954fa79c970c303424f3af>:0)
EFT.Player+FirearmController+GClass1593.MakeShot (BulletClass ammo, System.Int32 chamberIndex, System.Boolean multiBarrelShot) (at <8a5b326544954fa79c970c303424f3af>:0)
EFT.Player+FirearmController+GClass1594.InternalOnFireEvent () (at <8a5b326544954fa79c970c303424f3af>:0)
EFT.Player+FirearmController+GClass1594.method_10 (System.Single normalizedStartFrameTime, System.Single normalizedEndFrameTime) (at <8a5b326544954fa79c970c303424f3af>:0)
EFT.Player+FirearmController+GClass1594.Update (System.Single deltaTime) (at <8a5b326544954fa79c970c303424f3af>:0)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
Class312:UnityEngine.ILogHandler.LogException(Exception, Object)
UnityEngine.Debug:LogException(Exception)
EFT.GClass1594:Update(Single)
EFT.ItemHandsController:ManualUpdate(Single)
EFT.FirearmController:ManualUpdate(Single)
EFT.Player:ArmsUpdate(Single)
EFT.Player:ComplexUpdate(EUpdateQueue, Single)
EFT.Player:UpdateTick()
EFT.Class792:method_6(Player)
EFT.GameWorld:SafePlayerOperation(Action`1)
EFT.GameWorld:PlayerTick(Single)
EFT.GameWorld:DoWorldTick(Single)
EFT.GameWorldUnityTickListener:Update()

At the same time, Ram usage increases by 0.2 to 0.8 gb per second until the game eventually crashes.
This behavior immediately stops once the punisher is killed in raid.

LogOutput file from directly after a raid where this happened:

[LogOutput.log](https://github.com/Solarint/SAIN/files/12505706/LogOutput.log)

Any help would be appreciated!
Thanks a bunch for making this mod, I already can't imagine playing without this anymore.

**Comment by Solarint** [comment]
Will be fixed in the next update.
