### ISSUE TITLE
Headshot protection not functional

### ISSUE THREAD

**Issue by UltraBlackLinux** [Solarint/SAIN#91]
I'm regularly getting headshot even with the headshot projection enabled - Is there something wrong? E.g. I'm peaking behing an object with my head barely sticking out, the bot locks in on me and gives me a headshot, all that at quite incredible speed
![image](https://github.com/Solarint/SAIN/assets/62404294/23dd0fea-5f37-4871-a7e0-3672bac0a833)

SPT 3.6.1
Algorithmic Level Progression, CustomSpawnPoints, MoreCheckmarks, NoDiscardLimit, SPT-Realism, SAIN, zzDrakiaXYZ-Waypoints

**Comment by Andrewgdewar** [comment]
Likely what is happening is the bullet spread is hitting you when the bots aim center mass. 
Basically the bot is likely not aiming at your head, but the spread variable makes the bullets fly around your torso, so can result in a headshot.
I've seen this on POOP and a number of other difficulty mods (including my own). 
But I'll see if the author thinks there is another thing going on.

**Comment by UltraBlackLinux** [comment]
I had that suspicion too but it's just too frequent

**Comment by Solarint** [comment]
It's not a perfect thing, and its not enabled by default intentionally. It's trying to find a middle ground between making the player never get headshot and doing nothing. May take some rework in other places to make this work as I want it.
