### ISSUE TITLE
Grandpa vision for bots

### ISSUE THREAD

**Issue by UltraBlackLinux** [Solarint/SAIN#92]
Okay, I'm incredibly bad at this game. This mod has helped me tremendously with it's reaction time, visibility and whatnot settings, but I'd like to make the bots even worse at the game, so I can have a little more fun (because just turning up the reaction time of the bot to infinity isn't quite what I'm  looking for. Bots are genuinely stupid 

My idea: Grandpa vision - The bot has a fixed (somewhat low) FOV for enemy detection, but can still spot movement in the corner of it's eye

**Comment by Solarint** [comment]
You can change bot's vision cone already in the sain config menu. Should be able to lower it to something much lower. (default is 160 iirc)
