### ISSUE TITLE
Error in raid prevents me from being able to shoot

### ISSUE THREAD

**Issue by Moetomdan** [Solarint/SAIN#93]
I am getting an error more frequently preventing me from shooting, however the server still thinks I fired a round. Am I just using a mod/plugin that is incompatible?

The SPT version I am using is 3.6.1
The Version of SAIN 2.0 I am using is 3.5.4, and I have it's dependencies up to date as well

Here is the error itself:
![ErrorCode](https://github.com/Solarint/SAIN/assets/51842993/a9d60395-851b-4b50-8f4d-058e56377133)

Here is my BepInEx log:
[LogOutput.log](https://github.com/Solarint/SAIN/files/12572577/LogOutput.log)

Here are my server mods:
![ServerMods1](https://github.com/Solarint/SAIN/assets/51842993/81eaacb0-ea41-4f18-a593-3b05afa84a78)
![ServerMods2](https://github.com/Solarint/SAIN/assets/51842993/e8c9927f-c33e-45d6-8244-5f6128252932)
![ServerMods3](https://github.com/Solarint/SAIN/assets/51842993/3e7a2acf-5da4-4218-b4d1-3ffe4f4e6c70)
![ServerMods4](https://github.com/Solarint/SAIN/assets/51842993/9c56c353-cb92-4897-a44c-2a5c6c3bec31)

Here are my BepInEx plugins:
![BepInExPlugins1](https://github.com/Solarint/SAIN/assets/51842993/c4c7e7b3-b93c-487f-ab27-24fab6d3cde5)
![BepInExPlugins2](https://github.com/Solarint/SAIN/assets/51842993/2785f042-4042-4553-8676-3145c15941cd)

**Comment by Solarint** [comment]
Since the issue isn't happening for anyone else, It's likely one of the gun mods you have not being set up like the default weapons.. If you can narrow it down to which one I can see if theres a change to fix the issue if its a compatibility thing.

**Comment by Moetomdan** [comment]
Apologies for the delay in my response. It appears to have been a compatibility issue with Jiro's Battery System. As after uninstalling that, the issue didn't appear once. However I will keep testing to make sure that it was exclusively that mod.

**Comment by Moetomdan** [comment]
Through further testing, I may have had an outdated/corrupted version of Jiro's Battery System. I reinstalled it and haven't had issues so far.
