### ISSUE TITLE
Plugin failed to load on startup.

### ISSUE THREAD

**Issue by notdeadtom** [Solarint/SAIN#95]
On launching the game I am given an error message that says "1 plugin failed to load due to errors.  Please check the console for details."

The console reads:
1 plugin failed to load due to errors:
Could not load [SAIN 3.5.4] because it has missing dependencies: xyz.drakia.waypoints (v1.2.0 or newer)

I am using SPT version 3.6.1

The mods I have installed are Priscilu 2.4.1, SVM 1.6.6, SAIN.2.0.Beta.3.5.4.for.3.6.1, DrakiaXYZ-Waypoints-1.2.0-3.6.0, and DrakiaXYZ-BigBrain-0.2.0_3.6.0

The error did not occur when I was only using SVM, Waypoints, and Priscilu.

[LogOutput.log](https://github.com/Solarint/SAIN/files/12706435/LogOutput.log)

**Comment by Solarint** [comment]
Waypoints is not installed correctly, as the error says.
You should have a folder called "DrakiaXYZ-Waypoints" in Bepinex/plugins. Inside that folder should be a file called "DrakiaXYZ-Waypoints.dll"

**Comment by ibratbk** [comment]
> Waypoints is not installed correctly, as the error says. You should have a folder called "DrakiaXYZ-Waypoints" in Bepinex/plugins. Inside that folder should be a file called "DrakiaXYZ-Waypoints.dll"

What should I do? Can I download DrakiaXYZ-Waypoints?
