### ISSUE TITLE
f6 key doesnt pull up menu

### ISSUE THREAD

**Issue by Viisfox** [Solarint/SAIN#97]
the f6 key does not pull up the menu for me the mod is installed correctly, but I'm not sure what is going on.

**Comment by Solarint** [comment]
Is there an entry for SAIN in the f12 bepinex menu? if so what does it say?

**Comment by Viisfox** [comment]
in f12 menu there is no sain entry for me its like mod isnt loaded. in console it says it loads correctly

**Comment by Viisfox** [comment]
![image](https://github.com/Solarint/SAIN/assets/147070315/ba77e312-e929-4057-b56e-415c486d5567)

**Comment by Solarint** [comment]
that is only the server mod, the client mod is not loading, check to make sure you have all required mods.

**Comment by Viisfox** [comment]
seems like bigbrain isnt loading idk how to fix it

**Comment by Viisfox** [comment]
idk i read on the bigbrain forums that if sain loads then bigbrain is working properly, so if bigbrain,sain and waypoints are loading successfully idk why it still isnt working ;/
