### ISSUE TITLE
that is only the server mod, the client mod is not loading, check to make sure you have all required mods.

### ISSUE THREAD

**Issue by Viisfox** [Solarint/SAIN#98]
that is only the server mod, the client mod is not loading, check to make sure you have all required mods.
so i have all the required mods including the other recommended mods like donuts and now im not getting pmcs or scav spawns instead of just sain not working. in the console thing it says all mods are loaded succesfully and i can play but when i press f12 only mods that pop up are weatherdebug and graphics adjuster and some BePindex thing, when i click advanced settings no new things pop up. f6 still brings up no menu. i also tried uninstalling the mods that are out of date to see if they were conflicting and still nothing
![Screenshot (2)](https://github.com/Solarint/SAIN/assets/147070315/7e3e5fe1-c9b3-418f-b6d7-ae377f8313bb)
![Screenshot (3)](https://github.com/Solarint/SAIN/assets/147070315/d168d0fe-4843-426a-93a2-1f11019b9845)

_Originally posted by @Solarint in https://github.com/Solarint/SAIN/issues/97#issuecomment-1749275412_

**Comment by Solarint** [comment]
upload your Bepinex/LogOutput file to pastebin after launching the game, the server window in your screenshot doesn't tell me much.

**Comment by Viisfox** [comment]
[LogOutput.log](https://github.com/Solarint/SAIN/files/12832316/LogOutput.log)
Herer is my log output file after i launched the game

**Comment by Solarint** [comment]
It's not even installed. It doesn't try to load bigbrain, sain, or waypoints.
Follow install instructions.

**Comment by Solarint** [comment]
your bepinex/plugins folder should have these files if installed correctly https://i.imgur.com/6iBY4By.png

**Comment by Viisfox** [comment]
> your bepinex/plugins folder should have these files if installed correctly https://i.imgur.com/6iBY4By.png

in my bepinex/plugins the files are there i see them, i dont know why they dont launch when i run the server launcher, not sure what the issue is i followed the install instructions still just doesnt load and not sure why.
