### ISSUE TITLE
your bepinex/plugins folder should have these files if installed correctly https://i.imgur.com/6iBY4By.png

### ISSUE THREAD

**Issue by Viisfox** [Solarint/SAIN#99]
your bepinex/plugins folder should have these files if installed correctly https://i.imgur.com/6iBY4By.png

_Originally posted by @Solarint in https://github.com/Solarint/SAIN/issues/98#issuecomment-1751801000_

**Comment by Viisfox** [comment]
idk what to say man, my folder looks exactly like that.
![image](https://github.com/Solarint/SAIN/assets/147070315/d98990a1-bee2-4306-a234-508b40075416)

**Comment by Solarint** [comment]
No idea, the install instructions are stupid simple. Something else is going on with your install.
